'use client';

import React from 'react';
import {
  Bell,
  ShieldAlert,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
  CheckCheck,
  Trash2,
} from 'lucide-react';
import { SecurityAlertRecord } from '@/types';

interface AlertCenterHeaderProps {
  alerts: SecurityAlertRecord[];
  onMarkAllRead: () => void;
  onSeedDefaults: () => void;
  onClearAll: () => void;
}

export const AlertCenterHeader: React.FC<AlertCenterHeaderProps> = ({
  alerts,
  onMarkAllRead,
  onSeedDefaults,
  onClearAll,
}) => {
  const criticalCount = alerts.filter((a) => a.severity === 'CRITICAL').length;
  const highCount = alerts.filter((a) => a.severity === 'HIGH').length;
  const mediumCount = alerts.filter((a) => a.severity === 'MEDIUM').length;
  const lowCount = alerts.filter((a) => a.severity === 'LOW').length;
  const unresolvedCount = alerts.filter((a) => a.status === 'NEW').length;
  const resolvedCount = alerts.filter((a) => a.status === 'RESOLVED').length;

  return (
    <div className="space-y-4">
      {/* Top Banner */}
      <div className="relative overflow-hidden rounded-2xl border border-cyan-500/30 bg-slate-950/90 p-5 backdrop-blur-xl shadow-[0_0_35px_rgba(6,182,212,0.08)]">
        <div className="pointer-events-none absolute -top-24 -left-24 h-64 w-64 rounded-full bg-rose-500/10 blur-3xl" />
        <div className="pointer-events-none absolute -bottom-24 -right-24 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl" />

        <div className="relative z-10 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-3.5">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl border border-rose-500/40 bg-gradient-to-br from-rose-500/20 to-orange-600/20 text-rose-400 shadow-[0_0_20px_rgba(244,63,94,0.3)]">
              <Bell className="h-6 w-6 animate-pulse" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2.5">
                <h1 className="font-mono text-xl font-bold tracking-wider text-slate-100 uppercase sm:text-2xl">
                  Security Alert Center
                </h1>
                <span className="inline-flex items-center gap-1.5 rounded-full border border-rose-500/40 bg-rose-500/10 px-3 py-0.5 font-mono text-[10px] font-semibold tracking-wider text-rose-300 uppercase shadow-[0_0_12px_rgba(244,63,94,0.2)]">
                  <span className="h-1.5 w-1.5 rounded-full bg-rose-400 animate-ping" />
                  Simulated SOC Telemetry
                </span>
              </div>
              <p className="mt-1 text-xs text-slate-400 sm:text-sm">
                Review simulated security events and detection triggers generated by the PhishGuard-AR analysis environment.
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={onSeedDefaults}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-900/80 px-3 py-1.5 font-mono text-xs font-semibold tracking-wider text-slate-300 uppercase transition-all duration-200 hover:border-slate-600 hover:text-slate-100"
            >
              <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
              <span>Seed Alerts</span>
            </button>

            <button
              type="button"
              onClick={onMarkAllRead}
              className="inline-flex items-center gap-1.5 rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-3 py-1.5 font-mono text-xs font-semibold tracking-wider text-cyan-300 uppercase transition-all duration-200 hover:bg-cyan-500/20"
            >
              <CheckCheck className="h-3.5 w-3.5" />
              <span>Mark All Read</span>
            </button>

            <button
              type="button"
              onClick={onClearAll}
              className="inline-flex items-center gap-1.5 rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-1.5 font-mono text-xs font-semibold tracking-wider text-rose-300 uppercase transition-all duration-200 hover:bg-rose-500/20"
            >
              <Trash2 className="h-3.5 w-3.5" />
              <span>Clear Alerts</span>
            </button>
          </div>
        </div>
      </div>

      {/* Stats Metric Cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6 font-mono text-xs">
        <div className="rounded-xl border border-rose-500/30 bg-rose-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-rose-400 uppercase">
            <span>Critical</span>
            <ShieldAlert className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-rose-400">{criticalCount}</div>
          <div className="text-[9px] text-rose-400/70">Immediate Action</div>
        </div>

        <div className="rounded-xl border border-orange-500/30 bg-orange-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-orange-400 uppercase">
            <span>High Risk</span>
            <AlertTriangle className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-orange-400">{highCount}</div>
          <div className="text-[9px] text-orange-400/70">Elevated Priority</div>
        </div>

        <div className="rounded-xl border border-amber-500/30 bg-amber-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-amber-400 uppercase">
            <span>Medium</span>
            <AlertTriangle className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-amber-400">{mediumCount}</div>
          <div className="text-[9px] text-amber-400/70">Standard Alert</div>
        </div>

        <div className="rounded-xl border border-blue-500/30 bg-blue-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-blue-400 uppercase">
            <span>Low Risk</span>
            <Bell className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-blue-400">{lowCount}</div>
          <div className="text-[9px] text-blue-400/70">Informational</div>
        </div>

        <div className="rounded-xl border border-cyan-500/30 bg-cyan-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-cyan-400 uppercase">
            <span>Unresolved</span>
            <Bell className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-cyan-400">{unresolvedCount}</div>
          <div className="text-[9px] text-cyan-400/70">Awaiting Action</div>
        </div>

        <div className="rounded-xl border border-emerald-500/30 bg-emerald-950/20 p-3 backdrop-blur-md">
          <div className="flex items-center justify-between text-[10px] text-emerald-400 uppercase">
            <span>Resolved</span>
            <CheckCircle2 className="h-3.5 w-3.5" />
          </div>
          <div className="mt-1 text-2xl font-bold text-emerald-400">{resolvedCount}</div>
          <div className="text-[9px] text-emerald-400/70">Contained / Verified</div>
        </div>
      </div>
    </div>
  );
};
