/**
 * PhishGuard-AR — Phase 8
 * Centralized AI Visualization Demo Dataset
 * 
 * 100% Frontend Only — Deterministic Conceptual Simulations
 * Labels: SIMULATED AI, CONCEPTUAL MODEL, SIMULATED INFERENCE, DEMO SCENARIOS
 */

import {
  NeuralLayerInfo,
  NeuralNodeData,
  NeuralConnectionData,
  SignalFusionItemData,
  AIThreatConstellationNode,
  AIExplainabilityNodeData,
  TokenAttentionItem,
  InferenceTimelineStep,
  AIDemoScenarioData,
} from '@/types';

export const AI_NEURAL_LAYERS: NeuralLayerInfo[] = [
  {
    id: 'layer-0',
    index: 0,
    name: 'Layer 0: Input Signals',
    shortName: 'Input',
    description: 'Raw ingested tokens, header anomalies, character encodings, and network telemetry metadata.',
    nodeCount: 4,
    color: '#06b6d4', // Cyan
  },
  {
    id: 'layer-1',
    index: 1,
    name: 'Layer 1: Text & Token Features',
    shortName: 'Text Features',
    description: 'N-gram extraction, TF-IDF lexical frequency vectors, and homoglyph/typo detection vectors.',
    nodeCount: 4,
    color: '#3b82f6', // Blue
  },
  {
    id: 'layer-2',
    index: 2,
    name: 'Layer 2: Structural Features',
    shortName: 'Structural',
    description: 'URL lexical entropy, domain age divergence, TLD anomalies, and HTML DOM structural markers.',
    nodeCount: 4,
    color: '#8b5cf6', // Violet
  },
  {
    id: 'layer-3',
    index: 3,
    name: 'Layer 3: Semantic Representation',
    shortName: 'Semantic',
    description: 'Multilingual DistilBERT transformer contextual embeddings and intent representations.',
    nodeCount: 4,
    color: '#ec4899', // Pink
  },
  {
    id: 'layer-4',
    index: 4,
    name: 'Layer 4: Robustness Analysis',
    shortName: 'Robustness',
    description: 'Adversarial perturbation bounds, gradient regularization invariance, and noise resistance.',
    nodeCount: 3,
    color: '#f59e0b', // Amber
  },
  {
    id: 'layer-5',
    index: 5,
    name: 'Layer 5: Signal Fusion',
    shortName: 'Fusion',
    description: 'Weighted Bayesian cross-layer multi-signal synthesis and confidence calibration.',
    nodeCount: 3,
    color: '#10b981', // Emerald
  },
  {
    id: 'layer-6',
    index: 6,
    name: 'Layer 6: Threat Decision',
    shortName: 'Decision',
    description: 'Conceptual multi-class threat categorization and calibrated confidence classification.',
    nodeCount: 2,
    color: '#ef4444', // Red / Rose
  },
];

export const AI_NEURAL_NODES: NeuralNodeData[] = [
  // Layer 0: Input Signals (x: -6)
  {
    id: 'n-0-0',
    layerIndex: 0,
    name: 'Raw UTF-8 Stream',
    layerName: 'Input Signals',
    role: 'Raw character stream ingestion and normalization',
    signalType: 'Token Ingestion',
    simulatedActivation: 0.95,
    contributionLevel: 'High',
    description: 'Simulated ingestion of raw email/URL payload characters with zero-width sanitization.',
    relatedSignals: ['Character Encodings', 'Tokenization', 'Header Metadata'],
    position: [-6, 2.2, 0],
    color: '#06b6d4',
  },
  {
    id: 'n-0-1',
    layerIndex: 0,
    name: 'Protocol & Headers',
    layerName: 'Input Signals',
    role: 'Transport envelope and header alignment',
    signalType: 'Header Analysis',
    simulatedActivation: 0.88,
    contributionLevel: 'Medium',
    description: 'Simulated header alignment checking SPF, DKIM, DMARC, and Return-Path signatures.',
    relatedSignals: ['DKIM Validation', 'SPF Alignment', 'Hop Latency'],
    position: [-6, 0.7, 0.5],
    color: '#06b6d4',
  },
  {
    id: 'n-0-2',
    layerIndex: 0,
    name: 'URL Query Anatomy',
    layerName: 'Input Signals',
    role: 'Lexical parsing of URL parameters',
    signalType: 'URL Lexical',
    simulatedActivation: 0.91,
    contributionLevel: 'High',
    description: 'Simulated segmentation of subdomains, path parameters, hex-escapes, and tracking hashes.',
    relatedSignals: ['Query Tokenizer', 'Subdomain Depth', 'Hex Decode'],
    position: [-6, -0.7, -0.5],
    color: '#06b6d4',
  },
  {
    id: 'n-0-3',
    layerIndex: 0,
    name: 'Visual DOM Structure',
    layerName: 'Input Signals',
    role: 'DOM layout and form input inspection',
    signalType: 'DOM Topology',
    simulatedActivation: 0.76,
    contributionLevel: 'Medium',
    description: 'Simulated detection of credential inputs, hidden iframe forms, and brand logo spoofing.',
    relatedSignals: ['Password Input Presence', 'Form Action URI', 'Logo Homoglyphs'],
    position: [-6, -2.2, 0],
    color: '#06b6d4',
  },

  // Layer 1: Text & Token Features (x: -4)
  {
    id: 'n-1-0',
    layerIndex: 1,
    name: 'Credential Keywords',
    layerName: 'Text Features',
    role: 'Lexical detection of login/password harvesting prompts',
    signalType: 'TF-IDF Lexical',
    simulatedActivation: 0.94,
    contributionLevel: 'High',
    description: 'Simulated lexical matching for authentication harvesting strings (e.g. "confirm password", "unlock account").',
    relatedSignals: ['Urgency Triggers', 'Verification Clues', 'Token Weights'],
    position: [-4, 2.3, 0.3],
    color: '#3b82f6',
  },
  {
    id: 'n-1-1',
    layerIndex: 1,
    name: 'Urgency & Pressure',
    layerName: 'Text Features',
    role: 'Psychological coercion and deadline framing',
    signalType: 'Psychological Signal',
    simulatedActivation: 0.89,
    contributionLevel: 'High',
    description: 'Simulated scoring for temporal deadlines ("within 24 hours", "immediate suspension warning").',
    relatedSignals: ['Account Lock Threat', 'Financial Penalty', 'Escalation Notice'],
    position: [-4, 0.8, -0.4],
    color: '#3b82f6',
  },
  {
    id: 'n-1-2',
    layerIndex: 1,
    name: 'Homoglyph & Levenshtein',
    layerName: 'Text Features',
    role: 'Cyrillic/Greek character substitution and typo-squatting',
    signalType: 'Homoglyph Signal',
    simulatedActivation: 0.82,
    contributionLevel: 'High',
    description: 'Simulated Unicode script confusable detection (e.g. Cyrillic "а" [U+0430] vs Latin "a" [U+0061]).',
    relatedSignals: ['Visual Confusables', 'Edit Distance', 'Zero-Width Injections'],
    position: [-4, -0.8, 0.4],
    color: '#3b82f6',
  },
  {
    id: 'n-1-3',
    layerIndex: 1,
    name: 'Sender Identity Drift',
    layerName: 'Text Features',
    role: 'Display name vs actual SMTP address dissonance',
    signalType: 'Identity Correlation',
    simulatedActivation: 0.85,
    contributionLevel: 'Medium',
    description: 'Simulated mismatch between authoritative brand display name and free webmail envelope.',
    relatedSignals: ['Brand Mapping', 'Lookalike Domains', 'Spoofed Headers'],
    position: [-4, -2.3, -0.3],
    color: '#3b82f6',
  },

  // Layer 2: Structural Features (x: -2)
  {
    id: 'n-2-0',
    layerIndex: 2,
    name: 'Shannon Entropy Vector',
    layerName: 'Structural Features',
    role: 'Randomness and algorithmic string generation check',
    signalType: 'Entropy Metric',
    simulatedActivation: 0.87,
    contributionLevel: 'High',
    description: 'Simulated bit-level Shannon entropy computation across subdomains and URL paths.',
    relatedSignals: ['DGA Classifier', 'Encoded Base64 Strings', 'Hex Patterns'],
    position: [-2, 2.2, -0.4],
    color: '#8b5cf6',
  },
  {
    id: 'n-2-1',
    layerIndex: 2,
    name: 'Domain Registrar Delta',
    layerName: 'Structural Features',
    role: 'Domain age vs brand authority correlation',
    signalType: 'WHOIS & Age',
    simulatedActivation: 0.91,
    contributionLevel: 'High',
    description: 'Simulated domain telemetry showing registration age < 48 hours imitating a 20-year brand.',
    relatedSignals: ['Newly Registered Domains', 'Privacy Guard', 'Registrar Risk'],
    position: [-2, 0.7, 0.5],
    color: '#8b5cf6',
  },
  {
    id: 'n-2-2',
    layerIndex: 2,
    name: 'Redirect Chain Graph',
    layerName: 'Structural Features',
    role: 'Multi-hop HTTP 30x cloaking analysis',
    signalType: 'Redirect Analysis',
    simulatedActivation: 0.79,
    contributionLevel: 'Medium',
    description: 'Simulated graph traversal identifying open redirects and dynamic geo-targeted cloaking pages.',
    relatedSignals: ['Open Redirects', 'Shortener Traversal', 'Cloaking Detection'],
    position: [-2, -0.7, -0.3],
    color: '#8b5cf6',
  },
  {
    id: 'n-2-3',
    layerIndex: 2,
    name: 'Anchor Text Mismatch',
    layerName: 'Structural Features',
    role: 'Visible hyperlink destination vs actual href destination',
    signalType: 'Hyperlink Forensics',
    simulatedActivation: 0.93,
    contributionLevel: 'High',
    description: 'Simulated detection of href attribute pointing to malicious IP while anchor text reads "https://microsoft.com".',
    relatedSignals: ['Deceptive Link', 'Mismatched Target', 'Obfuscated Host'],
    position: [-2, -2.2, 0.4],
    color: '#8b5cf6',
  },

  // Layer 3: Semantic Representation (x: 0)
  {
    id: 'n-3-0',
    layerIndex: 3,
    name: 'Transformer Attention Pool',
    layerName: 'Semantic Representation',
    role: 'Self-attention matrix over multi-lingual tokens',
    signalType: 'Contextual Attention',
    simulatedActivation: 0.96,
    contributionLevel: 'High',
    description: 'Simulated 12-layer multi-head self-attention focusing on intent and urgency token clusters.',
    relatedSignals: ['Attention Heads', 'Contextual Vectors', 'Subword Embeddings'],
    position: [0, 2.2, 0.5],
    color: '#ec4899',
  },
  {
    id: 'n-3-1',
    layerIndex: 3,
    name: 'Cross-Lingual Embedding',
    layerName: 'Semantic Representation',
    role: 'Semantic invariant projection across 100+ languages',
    signalType: 'Multilingual Space',
    simulatedActivation: 0.88,
    contributionLevel: 'High',
    description: 'Simulated language-agnostic vector mapping translating German, Spanish, French, and Japanese threat intents.',
    relatedSignals: ['XLM-RoBERTa Vectors', 'Cross-Lingual Alignment', 'Translation Invariance'],
    position: [0, 0.7, -0.5],
    color: '#ec4899',
  },
  {
    id: 'n-3-2',
    layerIndex: 3,
    name: 'Brand Latent Space',
    layerName: 'Semantic Representation',
    role: 'Implicit brand association vs explicit signature',
    signalType: 'Latent Similarity',
    simulatedActivation: 0.92,
    contributionLevel: 'High',
    description: 'Simulated cosine similarity in latent space indicating high intent mimicry of Global Banking services.',
    relatedSignals: ['Brand Vectors', 'Cosine Distance', 'Semantic Archetypes'],
    position: [0, -0.7, 0.4],
    color: '#ec4899',
  },
  {
    id: 'n-3-3',
    layerIndex: 3,
    name: 'Action Trigger Intent',
    layerName: 'Semantic Representation',
    role: 'Intent classification of call-to-action vectors',
    signalType: 'Intent Vector',
    simulatedActivation: 0.94,
    contributionLevel: 'High',
    description: 'Simulated classification of the primary intent as "Forced External Authentication".',
    relatedSignals: ['Action Framing', 'Phishing Intent', 'Compliance Pressure'],
    position: [0, -2.2, -0.4],
    color: '#ec4899',
  },

  // Layer 4: Robustness Analysis (x: 2)
  {
    id: 'n-4-0',
    layerIndex: 4,
    name: 'Perturbation Filter',
    layerName: 'Robustness Analysis',
    role: 'Sanitization of adversarial homoglyphs and zero-width noise',
    signalType: 'Adversarial Defense',
    simulatedActivation: 0.92,
    contributionLevel: 'High',
    description: 'Simulated defensiveness against character substitutions, space insertions, and leetspeak mutations.',
    relatedSignals: ['Homoglyph Canonicalizer', 'Noise Invariance', 'Gradient Hardening'],
    position: [2, 1.8, -0.3],
    color: '#f59e0b',
  },
  {
    id: 'n-4-1',
    layerIndex: 4,
    name: 'Semantic Invariance Guard',
    layerName: 'Robustness Analysis',
    role: 'Preservation of threat verdict across synonym perturbations',
    signalType: 'Embedding Defense',
    simulatedActivation: 0.89,
    contributionLevel: 'High',
    description: 'Simulated stability check verifying that masking non-critical tokens does not flip the classification.',
    relatedSignals: ['FGSM Invariance', 'Synonym Replacement', 'Bounded Epsilon'],
    position: [2, 0, 0.4],
    color: '#f59e0b',
  },
  {
    id: 'n-4-2',
    layerIndex: 4,
    name: 'Confidence Regularizer',
    layerName: 'Robustness Analysis',
    role: 'Prevention of adversarial overconfidence / underconfidence',
    signalType: 'Calibration',
    simulatedActivation: 0.95,
    contributionLevel: 'High',
    description: 'Simulated Platt scaling and temperature adjustment maintaining truthful uncertainty bounds.',
    relatedSignals: ['Temperature Scaling', 'Uncertainty Estimation', 'Ensemble Smoothing'],
    position: [2, -1.8, -0.3],
    color: '#f59e0b',
  },

  // Layer 5: Signal Fusion (x: 4)
  {
    id: 'n-5-0',
    layerIndex: 5,
    name: 'Multi-Modal Integrator',
    layerName: 'Signal Fusion',
    role: 'Cross-signal Bayesian weighting and risk aggregation',
    signalType: 'Bayesian Fusion',
    simulatedActivation: 0.96,
    contributionLevel: 'High',
    description: 'Simulated weighted synthesis uniting text features, structural anomalies, and semantic embeddings.',
    relatedSignals: ['Weighted Ensembles', 'Cross-Validation Gates', 'Evidence Synthesis'],
    position: [4, 1.5, 0.3],
    color: '#10b981',
  },
  {
    id: 'n-5-1',
    layerIndex: 5,
    name: 'Confidence Calibrator',
    layerName: 'Signal Fusion',
    role: 'Empirical risk calibration against historical telemetry',
    signalType: 'Risk Calibration',
    simulatedActivation: 0.94,
    contributionLevel: 'High',
    description: 'Simulated calibration adjusting threat score to 96.4% confidence based on signal concordance.',
    relatedSignals: ['Concordance Scoring', 'False Positive Suppressor', 'Risk Boundary'],
    position: [4, 0, -0.4],
    color: '#10b981',
  },
  {
    id: 'n-5-2',
    layerIndex: 5,
    name: 'Explainability Attributor',
    layerName: 'Signal Fusion',
    role: 'Simulated evidence contribution decomposition',
    signalType: 'Attribution Engine',
    simulatedActivation: 0.91,
    contributionLevel: 'High',
    description: 'Simulated attribution attributing 38% risk to credential keywords and 32% to URL structural spoofing.',
    relatedSignals: ['Feature Attributions', 'Evidence Graph', 'Reasoning Trace'],
    position: [4, -1.5, 0.3],
    color: '#10b981',
  },

  // Layer 6: Threat Decision (x: 6)
  {
    id: 'n-6-0',
    layerIndex: 6,
    name: 'Phishing Threat Verdict',
    layerName: 'Threat Decision',
    role: 'Final simulated high-risk malicious classification',
    signalType: 'Primary Verdict',
    simulatedActivation: 0.96,
    contributionLevel: 'High',
    description: 'Simulated classification: High confidence malicious phishing payload targeting corporate credentials.',
    relatedSignals: ['Threat Category', 'Block Recommendation', 'Security Orchestration'],
    position: [6, 0.8, 0],
    color: '#ef4444',
  },
  {
    id: 'n-6-1',
    layerIndex: 6,
    name: 'Mitigation Recommendation',
    layerName: 'Threat Decision',
    role: 'Automated quarantine and defense guidance dispatch',
    signalType: 'Policy Action',
    simulatedActivation: 0.95,
    contributionLevel: 'High',
    description: 'Simulated action: Automated email quarantine, domain firewall sinkhole, and credential reset ticket.',
    relatedSignals: ['Firewall Sinkhole', 'SIEM Notification', 'User Awareness Alert'],
    position: [6, -0.8, 0],
    color: '#ef4444',
  },
];

// Generate deterministic connections between adjacent layers
export function generateDemoConnections(): NeuralConnectionData[] {
  const connections: NeuralConnectionData[] = [];
  const nodesByLayer: { [layer: number]: NeuralNodeData[] } = {};

  AI_NEURAL_NODES.forEach((node) => {
    if (!nodesByLayer[node.layerIndex]) {
      nodesByLayer[node.layerIndex] = [];
    }
    nodesByLayer[node.layerIndex].push(node);
  });

  for (let l = 0; l < 6; l++) {
    const currentLayer = nodesByLayer[l] || [];
    const nextLayer = nodesByLayer[l + 1] || [];

    currentLayer.forEach((fromNode) => {
      nextLayer.forEach((toNode) => {
        const weight = Number((0.4 + ((fromNode.id.charCodeAt(2) + toNode.id.charCodeAt(2)) % 60) / 100).toFixed(2));
        connections.push({
          id: `conn-${fromNode.id}-${toNode.id}`,
          fromNodeId: fromNode.id,
          toNodeId: toNode.id,
          fromPosition: fromNode.position,
          toPosition: toNode.position,
          weight,
          isActive: weight > 0.6,
          pulseSpeed: 1.0 + weight * 1.5,
          color: fromNode.color,
        });
      });
    });
  }

  return connections;
}

export const AI_NEURAL_CONNECTIONS = generateDemoConnections();

export const AI_SIGNAL_FUSION_ITEMS: SignalFusionItemData[] = [
  {
    id: 'sig-cred',
    name: 'Credential Language',
    category: 'Text Semantics',
    simulatedStrength: 0.94,
    description: 'Explicit request for login credentials, passwords, or Multi-Factor Authentication tokens.',
    weight: 0.22,
    status: 'CRITICAL',
    color: '#ef4444',
  },
  {
    id: 'sig-url',
    name: 'URL Structure & Entropy',
    category: 'Structural',
    simulatedStrength: 0.91,
    description: 'High Shannon entropy, lookalike TLDs, multiple subdomains, and embedded obfuscations.',
    weight: 0.20,
    status: 'CRITICAL',
    color: '#f97316',
  },
  {
    id: 'sig-urgency',
    name: 'Urgency & Coercion',
    category: 'Psychological',
    simulatedStrength: 0.88,
    description: 'Artificial time pressure, account suspension threats, and immediate action demands.',
    weight: 0.16,
    status: 'WARNING',
    color: '#eab308',
  },
  {
    id: 'sig-brand',
    name: 'Brand Impersonation',
    category: 'Visual & Identity',
    simulatedStrength: 0.92,
    description: 'Mimicry of recognized corporate brands, logos, headers, and visual assets.',
    weight: 0.18,
    status: 'CRITICAL',
    color: '#ec4899',
  },
  {
    id: 'sig-char',
    name: 'Character Anomalies',
    category: 'Homoglyph & Unicode',
    simulatedStrength: 0.82,
    description: 'Cyrillic script confusables, zero-width spaces, and leetspeak character substitutions.',
    weight: 0.12,
    status: 'WARNING',
    color: '#8b5cf6',
  },
  {
    id: 'sig-domain',
    name: 'Domain Consistency',
    category: 'Network Telemetry',
    simulatedStrength: 0.89,
    description: 'Mismatch between sender domain, return path, and target authentication endpoints.',
    weight: 0.14,
    status: 'CRITICAL',
    color: '#06b6d4',
  },
  {
    id: 'sig-drift',
    name: 'Semantic Intent Drift',
    category: 'Transformer NLP',
    simulatedStrength: 0.78,
    description: 'Divergence between legitimate business communication baseline and coercive payload.',
    weight: 0.10,
    status: 'WARNING',
    color: '#3b82f6',
  },
  {
    id: 'sig-payment',
    name: 'Payment & Invoice Clues',
    category: 'Transactional',
    simulatedStrength: 0.74,
    description: 'Fraudulent wire instructions, overdue invoice urgency, and fake transaction IDs.',
    weight: 0.08,
    status: 'ELEVATED',
    color: '#10b981',
  },
];

export const AI_THREAT_CONSTELLATION_NODES: AIThreatConstellationNode[] = [
  {
    id: 'threat-cred',
    name: 'Credential Harvesting',
    category: 'Authentication Attacks',
    riskLevel: 'CRITICAL',
    simulatedFrequency: '42.8%',
    associatedSignals: ['Credential Language', 'Urgency', 'Anchor Text Mismatch'],
    robustnessExposure: 'Moderate — vulnerable to zero-width obfuscation without Phase 6 hardening',
    defenseStrategy: 'Adversarial token canonicalization & structural form analysis',
    position: [0, 2.5, 0],
    connections: ['threat-brand', 'threat-url', 'threat-social'],
    color: '#ef4444',
  },
  {
    id: 'threat-brand',
    name: 'Brand Impersonation',
    category: 'Identity Spoofing',
    riskLevel: 'CRITICAL',
    simulatedFrequency: '28.4%',
    associatedSignals: ['Brand Impersonation', 'Domain Consistency', 'Homoglyphs'],
    robustnessExposure: 'High — typo-squatted domains evade basic lexical checks',
    defenseStrategy: 'Latent space cosine similarity & multi-modal logo recognition',
    position: [2.5, 1.2, 0.8],
    connections: ['threat-cred', 'threat-url', 'threat-payment'],
    color: '#ec4899',
  },
  {
    id: 'threat-url',
    name: 'Malicious URL / Cloaking',
    category: 'Infrastructure',
    riskLevel: 'CRITICAL',
    simulatedFrequency: '36.1%',
    associatedSignals: ['URL Structure', 'Shannon Entropy', 'Redirect Chains'],
    robustnessExposure: 'High — multi-hop redirects and IP encoding disguise hosts',
    defenseStrategy: 'Recursive headless link unfurling & entropy thresholding',
    position: [2.0, -1.5, -0.6],
    connections: ['threat-cred', 'threat-brand', 'threat-unicode'],
    color: '#f97316',
  },
  {
    id: 'threat-payment',
    name: 'Payment & Invoice Fraud',
    category: 'Financial Engineering',
    riskLevel: 'HIGH',
    simulatedFrequency: '16.7%',
    associatedSignals: ['Payment Clues', 'Urgency', 'Sender Identity Drift'],
    robustnessExposure: 'Moderate — conversational tone evades spam filters',
    defenseStrategy: 'Contextual semantic role labeling & transaction verification',
    position: [0, -2.4, 0.5],
    connections: ['threat-brand', 'threat-social'],
    color: '#eab308',
  },
  {
    id: 'threat-social',
    name: 'Social Engineering',
    category: 'Behavioral Manipulation',
    riskLevel: 'HIGH',
    simulatedFrequency: '31.2%',
    associatedSignals: ['Urgency & Coercion', 'Semantic Drift', 'Authority Triggers'],
    robustnessExposure: 'High — subtle phrasing variations bypass static rules',
    defenseStrategy: 'Multilingual DistilBERT intent classification',
    position: [-2.2, -1.3, 0.7],
    connections: ['threat-cred', 'threat-payment', 'threat-unicode'],
    color: '#8b5cf6',
  },
  {
    id: 'threat-unicode',
    name: 'Unicode & Homoglyphs',
    category: 'Evasion Techniques',
    riskLevel: 'ELEVATED',
    simulatedFrequency: '19.5%',
    associatedSignals: ['Character Anomalies', 'Homoglyph Signal', 'Zero-Width Tokens'],
    robustnessExposure: 'Critical — standard NLP tokenizers crash or misclassify',
    defenseStrategy: 'Adversarial Unicode normalization & confusable mapping',
    position: [-2.4, 1.4, -0.5],
    connections: ['threat-url', 'threat-social', 'threat-cred'],
    color: '#06b6d4',
  },
  {
    id: 'threat-benign',
    name: 'Benign Corporate Comms',
    category: 'Legitimate Traffic',
    riskLevel: 'LOW',
    simulatedFrequency: '68.0%',
    associatedSignals: ['DKIM Valid', 'Consistent Sender', 'Low Entropy'],
    robustnessExposure: 'Low — verified legitimate baseline with standard signatures',
    defenseStrategy: 'Zero-trust whitelist verification & signature pinning',
    position: [0, 0, -2.2],
    connections: ['threat-social'],
    color: '#10b981',
  },
];

export const AI_EXPLAINABILITY_NODES: AIExplainabilityNodeData[] = [
  {
    id: 'exp-1',
    label: 'Urgent Account Suspension Notice',
    category: 'Input Evidence',
    simulatedContribution: 0.18,
    description: 'Header text phrases: "Your corporate account will be suspended within 24 hours".',
    parentIds: [],
    status: 'ACTIVE',
  },
  {
    id: 'exp-2',
    label: 'Credential Verification Link',
    category: 'Input Evidence',
    simulatedContribution: 0.24,
    description: 'CTA directs to an unverified third-party host imitating enterprise SSO portal.',
    parentIds: [],
    status: 'ACTIVE',
  },
  {
    id: 'exp-3',
    label: 'Mismatched Target URL',
    category: 'Structural Feature',
    simulatedContribution: 0.22,
    description: 'Anchor claims "login.microsoftonline.com" while destination resolves to "auth-verify892.top".',
    parentIds: ['exp-2'],
    status: 'ACTIVE',
  },
  {
    id: 'exp-4',
    label: 'Homoglyph Cyrillic Character Injections',
    category: 'Adversarial Evasion',
    simulatedContribution: 0.14,
    description: 'Replaced Latin "o" with Cyrillic "о" (U+043E) to confuse lexical filters.',
    parentIds: ['exp-1'],
    status: 'ACTIVE',
  },
  {
    id: 'exp-5',
    label: 'Signal Fusion Consensus',
    category: 'Model Reasoning',
    simulatedContribution: 0.96,
    description: 'Both Lexical SVM and Multilingual Transformer models indicate >94% malicious probability.',
    parentIds: ['exp-1', 'exp-2', 'exp-3', 'exp-4'],
    status: 'ACTIVE',
  },
  {
    id: 'exp-6',
    label: 'Final Verdict: PHISHING (96.4%)',
    category: 'Simulated Decision',
    simulatedContribution: 0.964,
    description: 'High-risk malicious credential harvesting attack targeting corporate identity.',
    parentIds: ['exp-5'],
    status: 'ACTIVE',
  },
];

export const AI_INFERENCE_TIMELINE_STEPS: InferenceTimelineStep[] = [
  {
    stepNumber: 1,
    timecode: '00:00.12',
    title: 'Input Ingested & Sanitized',
    layer: 'Layer 0: Input Signals',
    description: 'Raw payload stream decoded; zero-width spaces and control characters stripped.',
    simulatedDurationMs: 350,
    status: 'READY',
  },
  {
    stepNumber: 2,
    timecode: '00:00.48',
    title: 'Text & Lexical Features Extracted',
    layer: 'Layer 1: Text Features',
    description: 'N-grams generated, TF-IDF vectors calculated, and homoglyph scripts cataloged.',
    simulatedDurationMs: 400,
    status: 'READY',
  },
  {
    stepNumber: 3,
    timecode: '00:00.89',
    title: 'Structural & Domain Forensics',
    layer: 'Layer 2: Structural Features',
    description: 'URL Shannon entropy measured, redirect chain unfurled, WHOIS age delta computed.',
    simulatedDurationMs: 450,
    status: 'READY',
  },
  {
    stepNumber: 4,
    timecode: '00:01.35',
    title: 'Transformer Semantic Projection',
    layer: 'Layer 3: Semantic Representation',
    description: 'Multilingual DistilBERT embeddings generated; self-attention matrix focused on coercion intent.',
    simulatedDurationMs: 500,
    status: 'READY',
  },
  {
    stepNumber: 5,
    timecode: '00:01.88',
    title: 'Adversarial Robustness Hardening',
    layer: 'Layer 4: Robustness Analysis',
    description: 'Perturbation bounds tested; invariance guards neutralize homoglyph and synonym evasions.',
    simulatedDurationMs: 450,
    status: 'READY',
  },
  {
    stepNumber: 6,
    timecode: '00:02.32',
    title: 'Multi-Modal Signal Fusion',
    layer: 'Layer 5: Signal Fusion',
    description: 'Bayesian weighting unifies lexical vectors, structural anomalies, and semantic representations.',
    simulatedDurationMs: 400,
    status: 'READY',
  },
  {
    stepNumber: 7,
    timecode: '00:02.75',
    title: 'Threat Categorization & Verdict',
    layer: 'Layer 6: Threat Decision',
    description: 'Calibrated confidence classification outputs 96.4% Phishing risk; quarantine recommended.',
    simulatedDurationMs: 350,
    status: 'READY',
  },
  {
    stepNumber: 8,
    timecode: '00:03.10',
    title: 'Explainability Graph Generated',
    layer: 'Explainability Core',
    description: 'Simulated evidence contribution graph compiled for security operations review.',
    simulatedDurationMs: 300,
    status: 'READY',
  },
];

export const AI_DEMO_SCENARIOS: AIDemoScenarioData[] = [
  {
    id: 'scenario-cred',
    name: 'Credential Harvesting Attack',
    category: 'Corporate Impersonation',
    sampleInput: 'URGENT: Your Microsoft 365 security token has expired. Re-authenticate immediately at https://auth-verify892.top/login to prevent service termination.',
    verdict: 'PHISHING',
    confidenceScore: 0.964,
    threatLevel: 'CRITICAL',
    robustnessScore: 0.92,
    explanationSummary: 'High-confidence credential harvesting attack combining urgent tone, lookalike brand signatures, and high-entropy external domain.',
    tokens: [
      { token: 'URGENT:', weight: 0.88, category: 'Psychological Urgency', isPerturbed: false },
      { token: 'Your', weight: 0.12, category: 'Neutral', isPerturbed: false },
      { token: 'Microsoft', weight: 0.94, category: 'Brand Mimicry', isPerturbed: false },
      { token: '365', weight: 0.65, category: 'Brand Mimicry', isPerturbed: false },
      { token: 'security', weight: 0.72, category: 'Security Framing', isPerturbed: false },
      { token: 'token', weight: 0.68, category: 'Authentication Prompt', isPerturbed: false },
      { token: 'has', weight: 0.05, category: 'Neutral', isPerturbed: false },
      { token: 'expired.', weight: 0.85, category: 'Urgency Pressure', isPerturbed: false },
      { token: 'Re-authenticate', weight: 0.96, category: 'Credential Harvesting', isPerturbed: false },
      { token: 'immediately', weight: 0.91, category: 'Psychological Urgency', isPerturbed: false },
      { token: 'at', weight: 0.04, category: 'Neutral', isPerturbed: false },
      { token: 'https://auth-verify892.top/login', weight: 0.97, category: 'Deceptive URL Target', isPerturbed: true },
      { token: 'to', weight: 0.03, category: 'Neutral', isPerturbed: false },
      { token: 'prevent', weight: 0.45, category: 'Coercion', isPerturbed: false },
      { token: 'service', weight: 0.38, category: 'Impact Threat', isPerturbed: false },
      { token: 'termination.', weight: 0.89, category: 'Threat Pressure', isPerturbed: false },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.96, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.94, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.91, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.93, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.76, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.89, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.82, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.45, status: 'NOMINAL' },
    ],
    primarySignals: ['Credential Language (96%)', 'URL Entropy (94%)', 'Brand Impersonation (93%)', 'Urgency Pressure (91%)'],
  },
  {
    id: 'scenario-bank',
    name: 'Fake Banking Security Alert',
    category: 'Financial Fraud',
    sampleInput: 'Chase Alert: An unauthorized wire transfer of $4,850.00 was attempted from your account. If this was not you, cancel transaction at https://secure-chase-protection.net.',
    verdict: 'PHISHING',
    confidenceScore: 0.952,
    threatLevel: 'CRITICAL',
    robustnessScore: 0.89,
    explanationSummary: 'Simulated fraudulent financial alert leveraging fear of monetary loss to redirect victim to an off-brand credential collector.',
    tokens: [
      { token: 'Chase', weight: 0.95, category: 'Brand Mimicry', isPerturbed: false },
      { token: 'Alert:', weight: 0.86, category: 'Security Framing', isPerturbed: false },
      { token: 'An', weight: 0.05, category: 'Neutral', isPerturbed: false },
      { token: 'unauthorized', weight: 0.92, category: 'Fear Induction', isPerturbed: false },
      { token: 'wire', weight: 0.84, category: 'Financial Context', isPerturbed: false },
      { token: 'transfer', weight: 0.81, category: 'Financial Context', isPerturbed: false },
      { token: 'of', weight: 0.02, category: 'Neutral', isPerturbed: false },
      { token: '$4,850.00', weight: 0.93, category: 'Financial Urgency', isPerturbed: false },
      { token: 'was', weight: 0.03, category: 'Neutral', isPerturbed: false },
      { token: 'attempted', weight: 0.77, category: 'Fear Induction', isPerturbed: false },
      { token: 'cancel', weight: 0.89, category: 'Call to Action', isPerturbed: false },
      { token: 'transaction', weight: 0.75, category: 'Financial Context', isPerturbed: false },
      { token: 'at', weight: 0.04, category: 'Neutral', isPerturbed: false },
      { token: 'https://secure-chase-protection.net', weight: 0.96, category: 'Deceptive URL Target', isPerturbed: true },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.91, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.95, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.94, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.96, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.62, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.92, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.79, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.95, status: 'CRITICAL' },
    ],
    primarySignals: ['Brand Impersonation (96%)', 'Payment Urgency (95%)', 'URL Structure (95%)', 'Psychological Panic (94%)'],
  },
  {
    id: 'scenario-corp',
    name: 'Corporate Payroll & Tax Notice',
    category: 'Executive Impersonation',
    sampleInput: 'Internal HR Update: Form W-2 tax documents for the current fiscal period are now available. Review your confidential earnings statement at https://hr-portal-internal.co/w2.',
    verdict: 'SUSPICIOUS',
    confidenceScore: 0.824,
    threatLevel: 'HIGH',
    robustnessScore: 0.86,
    explanationSummary: 'Simulated HR payroll lure with moderate suspicion. Domain lacks internal Active Directory federation signatures.',
    tokens: [
      { token: 'Internal', weight: 0.65, category: 'Authority Claim', isPerturbed: false },
      { token: 'HR', weight: 0.78, category: 'Corporate Function', isPerturbed: false },
      { token: 'Update:', weight: 0.42, category: 'Neutral', isPerturbed: false },
      { token: 'Form', weight: 0.55, category: 'Tax Documents', isPerturbed: false },
      { token: 'W-2', weight: 0.89, category: 'Tax Documents', isPerturbed: false },
      { token: 'tax', weight: 0.74, category: 'Tax Documents', isPerturbed: false },
      { token: 'documents', weight: 0.48, category: 'Neutral', isPerturbed: false },
      { token: 'confidential', weight: 0.71, category: 'Compliance Trigger', isPerturbed: false },
      { token: 'earnings', weight: 0.69, category: 'Financial Context', isPerturbed: false },
      { token: 'https://hr-portal-internal.co/w2', weight: 0.88, category: 'Off-Premise Link', isPerturbed: true },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.75, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.84, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.68, status: 'ELEVATED' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.72, status: 'ELEVATED' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.54, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.86, status: 'WARNING' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.70, status: 'ELEVATED' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.83, status: 'WARNING' },
    ],
    primarySignals: ['Domain Inconsistency (86%)', 'Off-Premise Target (84%)', 'Tax Lure Context (83%)', 'Credential Harvest (75%)'],
  },
  {
    id: 'scenario-multi',
    name: 'Multilingual Phishing Campaign',
    category: 'Cross-Border Phishing',
    sampleInput: 'WICHTIG: Ihr Deutsche Bank Sicherheitszertifikat läuft in 24 Stunden ab. Bitte aktualisieren Sie Ihre Zugangsdaten unter https://deutschebank-sicherheit.cloud/de.',
    verdict: 'PHISHING',
    confidenceScore: 0.946,
    threatLevel: 'CRITICAL',
    robustnessScore: 0.94,
    explanationSummary: 'German-language banking phish evaluated via Multilingual DistilBERT semantic representation with cross-lingual invariant classification.',
    tokens: [
      { token: 'WICHTIG:', weight: 0.91, category: 'Psychological Urgency', isPerturbed: false },
      { token: 'Ihr', weight: 0.15, category: 'Neutral', isPerturbed: false },
      { token: 'Deutsche', weight: 0.94, category: 'Brand Mimicry', isPerturbed: false },
      { token: 'Bank', weight: 0.92, category: 'Brand Mimicry', isPerturbed: false },
      { token: 'Sicherheitszertifikat', weight: 0.86, category: 'Security Framing', isPerturbed: false },
      { token: 'läuft', weight: 0.45, category: 'Neutral', isPerturbed: false },
      { token: 'in', weight: 0.05, category: 'Neutral', isPerturbed: false },
      { token: '24', weight: 0.89, category: 'Urgency Pressure', isPerturbed: false },
      { token: 'Stunden', weight: 0.85, category: 'Urgency Pressure', isPerturbed: false },
      { token: 'ab.', weight: 0.62, category: 'Neutral', isPerturbed: false },
      { token: 'Zugangsdaten', weight: 0.95, category: 'Credential Request', isPerturbed: false },
      { token: 'https://deutschebank-sicherheit.cloud/de', weight: 0.97, category: 'Deceptive URL Target', isPerturbed: true },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.95, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.93, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.90, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.95, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.68, status: 'ELEVATED' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.91, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.94, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.58, status: 'NOMINAL' },
    ],
    primarySignals: ['Zugangsdaten Credential Prompt (95%)', 'Brand Mimicry (95%)', 'Multilingual Intent (94%)', 'URL Obfuscation (93%)'],
  },
  {
    id: 'scenario-adv',
    name: 'Adversarial Homoglyph Mutation',
    category: 'Evasion Attack',
    sampleInput: 'Аttentiоn: Yоur PаyPаl ассоunt hаs bееn restriсted. Vеrify nоw: https://pаypаl-sесurе-lоgin.соm (Cyrillic homoglyphs embedded).',
    verdict: 'ADVERSARIAL',
    confidenceScore: 0.968,
    threatLevel: 'CRITICAL',
    robustnessScore: 0.95,
    explanationSummary: 'Heavily mutated payload using 14 Cyrillic confusable characters to evade standard ASCII classifiers. Neutralized by Phase 6 Adversarial Robustness Engine.',
    tokens: [
      { token: 'Аttentiоn:', weight: 0.92, category: 'Homoglyph Injected', isPerturbed: true },
      { token: 'Yоur', weight: 0.78, category: 'Homoglyph Injected', isPerturbed: true },
      { token: 'PаyPаl', weight: 0.98, category: 'Brand Homoglyph Spoof', isPerturbed: true },
      { token: 'ассоunt', weight: 0.91, category: 'Homoglyph Injected', isPerturbed: true },
      { token: 'hаs', weight: 0.42, category: 'Homoglyph Injected', isPerturbed: true },
      { token: 'bееn', weight: 0.38, category: 'Homoglyph Injected', isPerturbed: true },
      { token: 'restriсted.', weight: 0.94, category: 'Threat Pressure', isPerturbed: true },
      { token: 'Vеrify', weight: 0.96, category: 'Credential Prompt', isPerturbed: true },
      { token: 'nоw:', weight: 0.89, category: 'Urgency Pressure', isPerturbed: true },
      { token: 'https://pаypаl-sесurе-lоgin.соm', weight: 0.99, category: 'Adversarial Confusable Target', isPerturbed: true },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.96, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.97, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.92, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.98, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.99, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.94, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.91, status: 'CRITICAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.82, status: 'WARNING' },
    ],
    primarySignals: ['Character Homoglyphs (99%)', 'Brand Spoofing (98%)', 'URL Structure (97%)', 'Credential Request (96%)'],
  },
  {
    id: 'scenario-benign',
    name: 'Legitimate Corporate Meeting Request',
    category: 'Benign Control',
    sampleInput: 'Quarterly Product Review: Team, please review the attached slide deck ahead of our Thursday sync at 2:00 PM EST in Conference Room 4B.',
    verdict: 'SAFE',
    confidenceScore: 0.032,
    threatLevel: 'LOW',
    robustnessScore: 0.97,
    explanationSummary: 'Legitimate internal scheduling communication with zero adversarial markers, authentic sender verification, and absence of external authentication requests.',
    tokens: [
      { token: 'Quarterly', weight: 0.02, category: 'Business Context', isPerturbed: false },
      { token: 'Product', weight: 0.01, category: 'Business Context', isPerturbed: false },
      { token: 'Review:', weight: 0.01, category: 'Business Context', isPerturbed: false },
      { token: 'Team,', weight: 0.01, category: 'Neutral Greeting', isPerturbed: false },
      { token: 'please', weight: 0.02, category: 'Polite Request', isPerturbed: false },
      { token: 'review', weight: 0.03, category: 'Task Assignment', isPerturbed: false },
      { token: 'the', weight: 0.01, category: 'Neutral', isPerturbed: false },
      { token: 'attached', weight: 0.08, category: 'Attachment Context', isPerturbed: false },
      { token: 'slide', weight: 0.02, category: 'Business Asset', isPerturbed: false },
      { token: 'deck', weight: 0.01, category: 'Business Asset', isPerturbed: false },
      { token: 'ahead', weight: 0.02, category: 'Scheduling', isPerturbed: false },
      { token: 'of', weight: 0.01, category: 'Neutral', isPerturbed: false },
      { token: 'our', weight: 0.01, category: 'Neutral', isPerturbed: false },
      { token: 'Thursday', weight: 0.02, category: 'Calendar', isPerturbed: false },
      { token: 'sync', weight: 0.02, category: 'Calendar', isPerturbed: false },
    ],
    fusionSignals: [
      { ...AI_SIGNAL_FUSION_ITEMS[0], simulatedStrength: 0.03, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[1], simulatedStrength: 0.02, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[2], simulatedStrength: 0.04, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[3], simulatedStrength: 0.01, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[4], simulatedStrength: 0.00, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[5], simulatedStrength: 0.02, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[6], simulatedStrength: 0.05, status: 'NOMINAL' },
      { ...AI_SIGNAL_FUSION_ITEMS[7], simulatedStrength: 0.01, status: 'NOMINAL' },
    ],
    primarySignals: ['DKIM Verified (99%)', 'Zero External Credential Targets', 'Standard Business Lexicon', 'Zero Adversarial Noise'],
  },
];

export const aiVisualizationDemoData = {
  layers: AI_NEURAL_LAYERS,
  nodes: AI_NEURAL_NODES,
  connections: AI_NEURAL_CONNECTIONS,
  signals: AI_SIGNAL_FUSION_ITEMS,
  threats: AI_THREAT_CONSTELLATION_NODES,
  explanations: AI_EXPLAINABILITY_NODES,
  timeline: AI_INFERENCE_TIMELINE_STEPS,
  scenarios: AI_DEMO_SCENARIOS,
};
