/**
 * PhishGuard-AR — Phase 9
 * Centralized Security Alerts Demo Dataset
 * 
 * 100% Frontend-Only — Deterministic Demonstration Data
 */

import { SecurityAlertRecord } from '@/types';

export const DEMO_SECURITY_ALERTS: SecurityAlertRecord[] = [
  {
    id: 'ALT-9001',
    timestamp: '2026-09-18 14:42:08',
    severity: 'CRITICAL',
    category: 'HIGH_RISK_PHISHING',
    title: 'High-Risk Credential Harvesting Attack Detected',
    source: 'Inbound Gateway • Exchange Relay #04',
    threatType: 'Credential Harvesting',
    confidence: 96.4,
    explanation: 'Simulated multi-modal signal fusion identified high-urgency credential prompt targeting domain auth-verify892.top.',
    status: 'NEW',
    isRead: false,
    associatedScanId: 'PHG-0001',
  },
  {
    id: 'ALT-9002',
    timestamp: '2026-09-18 11:28:45',
    severity: 'CRITICAL',
    category: 'HOMOGRAPH_ATTACK_DETECTED',
    title: 'Adversarial Unicode Homoglyph Mutation Detected',
    source: 'Edge Web Filter • Proxy Node #02',
    threatType: 'Homoglyph Evasion',
    confidence: 96.8,
    explanation: '14 Cyrillic confusable characters identified in brand target (pаypаl-sесurе-lоgin.соm). Evasion neutralized by Phase 6 canonicalization.',
    status: 'NEW',
    isRead: false,
    associatedScanId: 'PHG-0003',
  },
  {
    id: 'ALT-9003',
    timestamp: '2026-09-18 13:15:32',
    severity: 'HIGH',
    category: 'HIGH_SEVERITY_EVENT',
    title: 'Financial Urgency & Wire Transfer Smishing Lure',
    source: 'Mobile Gateway • SMS Feed #01',
    threatType: 'Banking Impersonation',
    confidence: 95.2,
    explanation: 'Fraudulent $4,850.00 wire transfer alert attempting to induce panic redirect to secure-chase-protection.net.',
    status: 'ACKNOWLEDGED',
    isRead: true,
    associatedScanId: 'PHG-0002',
  },
  {
    id: 'ALT-9004',
    timestamp: '2026-09-17 12:44:28',
    severity: 'HIGH',
    category: 'URL_OBFUSCATION_DETECTED',
    title: 'Multi-Hop Nested URL Redirection Chain Blocked',
    source: 'DNS Resolver • Sensor Node #08',
    threatType: 'URL Cloaking',
    confidence: 98.1,
    explanation: 'Shortened Bitly link hid direct IP address destination hosting credential collector.',
    status: 'ACKNOWLEDGED',
    isRead: true,
    associatedScanId: 'PHG-0007',
  },
  {
    id: 'ALT-9005',
    timestamp: '2026-09-17 10:18:04',
    severity: 'MEDIUM',
    category: 'ROBUSTNESS_DEGRADATION',
    title: 'Baseline Model Confidence Drop Under Leetspeak',
    source: 'Robustness Lab • Engine Diagnostics',
    threatType: 'Model Resilience Drop',
    confidence: 68.4,
    explanation: 'Standard unhardened SVM experienced 25.8% confidence drop under character substitution. Hardened DistilBERT preserved 92% accuracy.',
    status: 'RESOLVED',
    isRead: true,
  },
  {
    id: 'ALT-9006',
    timestamp: '2026-09-16 16:22:50',
    severity: 'MEDIUM',
    category: 'UNUSUAL_SIGNAL_PATTERN',
    title: 'Typo-Squatted Courier Delivery Smishing Link',
    source: 'Perimeter Sensor • Inbound Mail Queue',
    threatType: 'Brand Impersonation',
    confidence: 88.7,
    explanation: 'Lookalike courier domain ("fedx-parcel-tracking.vip") identified with high TLD risk score.',
    status: 'RESOLVED',
    isRead: true,
    associatedScanId: 'PHG-0009',
  },
];
