// PHASE 7: SECURITY ANALYTICS & DASHBOARD DEMO DATA
// 100% Deterministic frontend simulation datasets across 24H, 7D, and 30D time ranges.
// Labeled as DEMO / SIMULATION / SIMULATED TELEMETRY / SIMULATED ANALYTICS

import { DashboardDataset, DashboardTimeRange } from '@/types';

export const DASHBOARD_DATA_24H: DashboardDataset = {
  timeRange: '24H',
  snapshotTimestamp: 'Simulation snapshot • 16:42:08',
  postureScore: 82,
  postureRating: 'HIGH RESILIENCE',
  postureSubMetrics: {
    threatDetection: 82,
    modelStability: 88,
    adversarialResilience: 79,
    defenseRecovery: 91,
    signalIntegrity: 86,
  },
  kpis: [
    {
      id: 'kpi-analyzed',
      label: 'Threats Analyzed',
      value: '12,842',
      numericValue: 12842,
      trend: '+14.8% today',
      trendType: 'positive',
      description: 'Incoming email, message, and URL payloads evaluated across simulated sensors',
      icon: 'ScanLine',
      sparkline: [35, 42, 58, 62, 74, 68, 85, 92, 110, 128],
      tag: 'SIMULATION',
    },
    {
      id: 'kpi-detected',
      label: 'Threats Flagged',
      value: '10,973',
      numericValue: 10973,
      trend: '+11.2% rate',
      trendType: 'positive',
      description: 'Phishing, social engineering, and adversarial evasion vectors intercepted',
      icon: 'ShieldAlert',
      sparkline: [28, 35, 48, 52, 60, 58, 72, 80, 95, 109],
      tag: 'SIMULATION',
    },
    {
      id: 'kpi-accuracy',
      label: 'Detection Accuracy',
      value: '94.7%',
      numericValue: 94.7,
      trend: '+2.8% benchmark',
      trendType: 'positive',
      description: 'Composite transformer and lexical baseline accuracy across test suite',
      icon: 'Cpu',
      sparkline: [91, 92, 92.5, 93, 93.8, 94.1, 94.2, 94.5, 94.6, 94.7],
      tag: 'SIMULATION',
    },
    {
      id: 'kpi-fpr',
      label: 'False Positive Rate',
      value: '2.4%',
      numericValue: 2.4,
      trend: '-0.7% decrease',
      trendType: 'positive',
      description: 'Benign communication misclassification frequency under ensemble voting',
      icon: 'AlertTriangle',
      sparkline: [3.8, 3.5, 3.2, 3.0, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4],
      tag: 'SIMULATION',
    },
    {
      id: 'kpi-robustness',
      label: 'Adversarial Robustness',
      value: '86.2%',
      numericValue: 86.2,
      trend: '+5.4% resilience',
      trendType: 'positive',
      description: 'Confidence retention under simulated Unicode, URL, and synonym attacks',
      icon: 'FlaskConical',
      sparkline: [76, 78, 80, 81, 82, 83.5, 84, 85, 85.8, 86.2],
      tag: 'SIMULATION',
    },
    {
      id: 'kpi-recovery',
      label: 'Defense Recovery',
      value: '91.8%',
      numericValue: 91.8,
      trend: '+7.1% restored',
      trendType: 'positive',
      description: 'Average confidence restored following AR normalization pipeline execution',
      icon: 'RefreshCw',
      sparkline: [82, 84, 85, 86.5, 88, 89, 89.5, 90.2, 91, 91.8],
      tag: 'SIMULATION',
    },
  ],
  threatActivity: [
    { timestamp: '00:00', timeLabel: '00:00', detected: 420, suspicious: 180, blocked: 340, total: 940 },
    { timestamp: '03:00', timeLabel: '03:00', detected: 310, suspicious: 140, blocked: 260, total: 710 },
    { timestamp: '06:00', timeLabel: '06:00', detected: 580, suspicious: 210, blocked: 490, total: 1280 },
    { timestamp: '09:00', timeLabel: '09:00', detected: 890, suspicious: 320, blocked: 780, total: 1990 },
    { timestamp: '12:00', timeLabel: '12:00', detected: 1120, suspicious: 410, blocked: 980, total: 2510 },
    { timestamp: '15:00', timeLabel: '15:00', detected: 1290, suspicious: 460, blocked: 1140, total: 2890 },
    { timestamp: '18:00', timeLabel: '18:00', detected: 980, suspicious: 350, blocked: 860, total: 2190 },
    { timestamp: '21:00', timeLabel: '21:00', detected: 620, suspicious: 240, blocked: 530, total: 1390 },
  ],
  severityDistribution: [
    {
      severity: 'CRITICAL',
      count: 1027,
      percentage: 8,
      color: '#ef4444',
      description: 'Zero-day spoofing & high-loss wire fraud',
    },
    {
      severity: 'HIGH',
      count: 2697,
      percentage: 21,
      color: '#f97316',
      description: 'Credential harvesting & lookalike SSO gateways',
    },
    {
      severity: 'MEDIUM',
      count: 3981,
      percentage: 31,
      color: '#eab308',
      description: 'Suspicious payment demands & urgency lures',
    },
    {
      severity: 'LOW',
      count: 2312,
      percentage: 18,
      color: '#38bdf8',
      description: 'Unverified newsletters & mild spam signals',
    },
    {
      severity: 'SAFE',
      count: 2825,
      percentage: 22,
      color: '#10b981',
      description: 'Verified benign corporate communications',
    },
  ],
  threatTypes: [
    {
      id: 'type-cred',
      name: 'Credential Harvesting',
      count: 3981,
      percentage: 31,
      severity: 'HIGH',
      affectedSignals: ['Credential Language', 'URL Structure', 'Brand References'],
      color: '#ef4444',
    },
    {
      id: 'type-brand',
      name: 'Brand Impersonation',
      count: 3082,
      percentage: 24,
      severity: 'HIGH',
      affectedSignals: ['Brand References', 'Lookalike Domains', 'Levenshtein Shift'],
      color: '#f97316',
    },
    {
      id: 'type-url',
      name: 'Malicious URL / Punycode',
      count: 2440,
      percentage: 19,
      severity: 'CRITICAL',
      affectedSignals: ['URL Structure', 'Domain Puncturing', 'IP Hex Encoding'],
      color: '#ec4899',
    },
    {
      id: 'type-social',
      name: 'Social Engineering Urgency',
      count: 1798,
      percentage: 14,
      severity: 'MEDIUM',
      affectedSignals: ['Urgency Language', 'Sentiment Modulation', 'Legal Coercion'],
      color: '#eab308',
    },
    {
      id: 'type-payment',
      name: 'Payment & Invoice Fraud',
      count: 899,
      percentage: 7,
      severity: 'HIGH',
      affectedSignals: ['Payment Clues', 'Unregistered Gateways', 'Wire Requests'],
      color: '#a855f7',
    },
    {
      id: 'type-homoglyph',
      name: 'Unicode / Homoglyph Evasion',
      count: 642,
      percentage: 5,
      severity: 'CRITICAL',
      affectedSignals: ['Character Anomalies', 'Cyrillic Mappings', 'Subword Splitting'],
      color: '#06b6d4',
    },
  ],
  detectionPerformance: {
    precision: 96.1,
    recall: 93.8,
    f1Score: 94.9,
    accuracy: 95.7,
    falsePositiveRate: 2.4,
    falseNegativeRate: 6.2,
    benchmarkModelName: 'Multilingual DistilBERT + BiLSTM',
    comparisonModelName: 'TF-IDF + Linear SVM Baseline',
  },
  modelComparison: [
    {
      attribute: 'Inference Latency',
      svmScore: 94,
      distilbertScore: 68,
      unit: 'pts',
      description: 'Linear SVM executes in <1ms; DistilBERT achieves ~18ms attention passes.',
    },
    {
      attribute: 'Signal Coverage',
      svmScore: 72,
      distilbertScore: 92,
      unit: 'pts',
      description: 'DistilBERT captures full bi-directional contextual dependencies across sentences.',
    },
    {
      attribute: 'Multilingual Handling',
      svmScore: 61,
      distilbertScore: 95,
      unit: 'pts',
      description: 'Contextual tokenizers generalize across 104 languages without translation.',
    },
    {
      attribute: 'Explainability Clarity',
      svmScore: 93,
      distilbertScore: 78,
      unit: 'pts',
      description: 'Linear weights provide exact feature coefficients; transformer attention requires integrated gradients.',
    },
    {
      attribute: 'Adversarial Robustness',
      svmScore: 38,
      distilbertScore: 89,
      unit: 'pts',
      description: 'Static SVM degrades severely under character swaps; DistilBERT retains semantic intent.',
    },
    {
      attribute: 'Composite Detection Score',
      svmScore: 74,
      distilbertScore: 96,
      unit: 'pts',
      description: 'Combined evaluation across noisy, obfuscated, and clean phishing benchmarks.',
    },
  ],
  robustness: {
    baselineStability: 94.8,
    underAttackStability: 68.4,
    confidenceRetention: 72.1,
    recoveryRate: 89.6,
    signalPreservation: 91.2,
    compositeRobustnessScore: 86.2,
    activeHardeningTechnique: 'Unicode NFKC Normalization + Transformer Hardening',
    status: 'ROBUST',
  },
  attackAnalytics: [
    {
      id: 'atk-homoglyph',
      name: 'Homoglyph Injection',
      attempts: 1284,
      confidenceDrop: -24.6,
      recoveryRate: 94.2,
      riskLevel: 'HIGH',
    },
    {
      id: 'atk-url',
      name: 'URL Obfuscation',
      attempts: 1073,
      confidenceDrop: -18.4,
      recoveryRate: 92.8,
      riskLevel: 'CRITICAL',
    },
    {
      id: 'atk-paraphrase',
      name: 'Semantic Paraphrasing',
      attempts: 892,
      confidenceDrop: -14.2,
      recoveryRate: 88.5,
      riskLevel: 'HIGH',
    },
    {
      id: 'atk-urgency',
      name: 'Urgency Mutation',
      attempts: 741,
      confidenceDrop: -11.8,
      recoveryRate: 86.1,
      riskLevel: 'MEDIUM',
    },
    {
      id: 'atk-format',
      name: 'Formatting Mutation',
      attempts: 520,
      confidenceDrop: -7.4,
      recoveryRate: 96.5,
      riskLevel: 'LOW',
    },
    {
      id: 'atk-token',
      name: 'Token Insertion Noise',
      attempts: 418,
      confidenceDrop: -9.2,
      recoveryRate: 91.0,
      riskLevel: 'MEDIUM',
    },
    {
      id: 'atk-brand',
      name: 'Brand Mutation',
      attempts: 392,
      confidenceDrop: -21.0,
      recoveryRate: 93.4,
      riskLevel: 'HIGH',
    },
  ],
  defenseEffectiveness: [
    {
      id: 'def-norm',
      name: 'Character Normalization (NFKC)',
      recoveryRate: 94.2,
      signalPreservation: 96.0,
      effectivenessRating: 'EXCELLENT',
      status: 'ACTIVE',
    },
    {
      id: 'def-url',
      name: 'URL Canonicalization & Punycode',
      recoveryRate: 92.8,
      signalPreservation: 93.5,
      effectivenessRating: 'EXCELLENT',
      status: 'ACTIVE',
    },
    {
      id: 'def-adv',
      name: 'Adversarial Training Augmentation',
      recoveryRate: 89.4,
      signalPreservation: 91.0,
      effectivenessRating: 'HIGH',
      status: 'ACTIVE',
    },
    {
      id: 'def-ens',
      name: 'Ensemble Verification (BERT+SVM)',
      recoveryRate: 91.0,
      signalPreservation: 94.2,
      effectivenessRating: 'EXCELLENT',
      status: 'CALIBRATED',
    },
    {
      id: 'def-ctx',
      name: 'Contextual Semantic Re-Analysis',
      recoveryRate: 86.5,
      signalPreservation: 88.0,
      effectivenessRating: 'HIGH',
      status: 'CALIBRATED',
    },
    {
      id: 'def-thr',
      name: 'Adaptive Threshold Calibration',
      recoveryRate: 84.0,
      signalPreservation: 86.2,
      effectivenessRating: 'HIGH',
      status: 'CALIBRATED',
    },
  ],
  securityTrends: [
    { timeLabel: '00:00', threatVolume: 940, detectionConfidence: 94.2, robustness: 84.1, defenseRecovery: 90.5 },
    { timeLabel: '03:00', threatVolume: 710, detectionConfidence: 94.8, robustness: 85.0, defenseRecovery: 91.0 },
    { timeLabel: '06:00', threatVolume: 1280, detectionConfidence: 93.9, robustness: 83.8, defenseRecovery: 89.8 },
    { timeLabel: '09:00', threatVolume: 1990, detectionConfidence: 95.1, robustness: 86.4, defenseRecovery: 91.5 },
    { timeLabel: '12:00', threatVolume: 2510, detectionConfidence: 94.6, robustness: 85.9, defenseRecovery: 91.2 },
    { timeLabel: '15:00', threatVolume: 2890, detectionConfidence: 94.7, robustness: 86.2, defenseRecovery: 91.8 },
    { timeLabel: '18:00', threatVolume: 2190, detectionConfidence: 95.3, robustness: 87.0, defenseRecovery: 92.4 },
    { timeLabel: '21:00', threatVolume: 1390, detectionConfidence: 94.9, robustness: 86.5, defenseRecovery: 91.9 },
  ],
  events: [
    {
      id: 'EVT-9812',
      timestamp: '16:41:08',
      eventType: 'PHISHING DETECTED',
      category: 'Credential Harvesting',
      shortDescription: 'Spoofed Microsoft 365 identity verification portal flagged',
      confidence: 96.4,
      threatLevel: 'phishing',
      severity: 'high',
      status: 'CONTAINED',
    },
    {
      id: 'EVT-9811',
      timestamp: '16:39:42',
      eventType: 'ROBUSTNESS TEST',
      category: 'Homoglyph Injection',
      shortDescription: 'Cyrillic character substitution evaluated under stress benchmark',
      confidence: 75.1,
      threatLevel: 'adversarial',
      severity: 'high',
      status: 'HARDENED',
    },
    {
      id: 'EVT-9810',
      timestamp: '16:37:19',
      eventType: 'DEFENSE SIMULATION',
      category: 'Character Normalization',
      shortDescription: 'NFKC canonical mapping recovered +28.2 confidence points',
      confidence: 94.8,
      threatLevel: 'safe',
      severity: 'safe',
      status: 'HARDENED',
    },
    {
      id: 'EVT-9809',
      timestamp: '16:35:54',
      eventType: 'SUSPICIOUS URL',
      category: 'URL Obfuscation',
      shortDescription: 'Bracket-punctured payment dispute link intercepted',
      confidence: 88.1,
      threatLevel: 'suspicious',
      severity: 'medium',
      status: 'ANALYZED',
    },
    {
      id: 'EVT-9808',
      timestamp: '16:31:27',
      eventType: 'SAFE MESSAGE',
      category: 'Corporate Notice',
      shortDescription: 'Internal engineering architecture synchronization verified benign',
      confidence: 99.2,
      threatLevel: 'safe',
      severity: 'safe',
      status: 'CLEAN',
    },
    {
      id: 'EVT-9807',
      timestamp: '16:28:10',
      eventType: 'BLOCKED PAYLOAD',
      category: 'Invoice Fraud',
      shortDescription: 'Overdue invoice wire intimidation payload quarantined',
      confidence: 97.8,
      threatLevel: 'blocked',
      severity: 'critical',
      status: 'QUARANTINED',
    },
  ],
  topSignals: [
    {
      id: 'sig-cred',
      signal: 'Credential Extraction Intent',
      category: 'Lexical Classifier',
      impactScore: 94,
      frequencyPercentage: 31,
      trend: 'up',
    },
    {
      id: 'sig-url',
      signal: 'Obfuscated Destination Domain',
      category: 'Network Routing',
      impactScore: 91,
      frequencyPercentage: 24,
      trend: 'up',
    },
    {
      id: 'sig-urgency',
      signal: 'Psychological Coercion / Urgency',
      category: 'Sentiment Modeling',
      impactScore: 86,
      frequencyPercentage: 19,
      trend: 'down',
    },
    {
      id: 'sig-brand',
      signal: 'Brand Trademark Levenshtein Shift',
      category: 'Trademark Verification',
      impactScore: 88,
      frequencyPercentage: 16,
      trend: 'up',
    },
    {
      id: 'sig-homoglyph',
      signal: 'Unicode Confusable Anomaly',
      category: 'Encoding Inspection',
      impactScore: 95,
      frequencyPercentage: 12,
      trend: 'up',
    },
    {
      id: 'sig-payment',
      signal: 'Monetary Extraction Language',
      category: 'Financial Risk Engine',
      impactScore: 82,
      frequencyPercentage: 9,
      trend: 'stable',
    },
    {
      id: 'sig-domain',
      signal: 'Subdomain Mismatch & Puncturing',
      category: 'DNS Heuristics',
      impactScore: 89,
      frequencyPercentage: 15,
      trend: 'up',
    },
    {
      id: 'sig-drift',
      signal: 'Semantic Embedding Drift',
      category: 'Transformer Attention',
      impactScore: 87,
      frequencyPercentage: 11,
      trend: 'stable',
    },
  ],
  aiInsightText:
    'Simulated telemetry indicates that credential-harvesting attacks remain the dominant vector (31% of flagged volume). Adversarial stress-testing shows highest initial degradation under Unicode homoglyph and URL obfuscation mutations, which are successfully restored (+28.2 pts) via the automated NFKC normalization defense pipeline.',
  postureBreakdown: [
    { axis: 'Threat Detection', score: 94, benchmark: 90, weight: 25 },
    { axis: 'Model Explainability', score: 88, benchmark: 80, weight: 15 },
    { axis: 'Adversarial Robustness', score: 86, benchmark: 75, weight: 20 },
    { axis: 'Defense Recovery Rate', score: 92, benchmark: 85, weight: 20 },
    { axis: 'Signal Preservation', score: 91, benchmark: 85, weight: 10 },
    { axis: 'Classifier Stability', score: 89, benchmark: 80, weight: 10 },
  ],
};

export const DASHBOARD_DATA_7D: DashboardDataset = {
  ...DASHBOARD_DATA_24H,
  timeRange: '7D',
  snapshotTimestamp: 'Simulation snapshot • 7-Day Cumulative',
  postureScore: 84,
  postureRating: 'HIGH RESILIENCE',
  kpis: [
    {
      ...DASHBOARD_DATA_24H.kpis[0],
      value: '84,620',
      numericValue: 84620,
      trend: '+8.4% weekly',
      sparkline: [210, 240, 280, 310, 340, 390, 420],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[1],
      value: '72,140',
      numericValue: 72140,
      trend: '+6.1% weekly',
      sparkline: [180, 210, 240, 260, 290, 340, 360],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[2],
      value: '95.1%',
      numericValue: 95.1,
      trend: '+1.4% weekly',
      sparkline: [93.5, 93.8, 94.2, 94.5, 94.8, 95.0, 95.1],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[3],
      value: '2.1%',
      numericValue: 2.1,
      trend: '-0.4% weekly',
      sparkline: [2.8, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[4],
      value: '87.4%',
      numericValue: 87.4,
      trend: '+3.2% weekly',
      sparkline: [82, 83.5, 84.8, 85.5, 86.2, 87.0, 87.4],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[5],
      value: '92.6%',
      numericValue: 92.6,
      trend: '+4.5% weekly',
      sparkline: [88, 89, 90.2, 91.0, 91.5, 92.1, 92.6],
    },
  ],
  threatActivity: [
    { timestamp: 'Day 1', timeLabel: 'Mon', detected: 8900, suspicious: 3200, blocked: 7800, total: 19900 },
    { timestamp: 'Day 2', timeLabel: 'Tue', detected: 11200, suspicious: 4100, blocked: 9800, total: 25100 },
    { timestamp: 'Day 3', timeLabel: 'Wed', detected: 12900, suspicious: 4600, blocked: 11400, total: 28900 },
    { timestamp: 'Day 4', timeLabel: 'Thu', detected: 9800, suspicious: 3500, blocked: 8600, total: 21900 },
    { timestamp: 'Day 5', timeLabel: 'Fri', detected: 13400, suspicious: 5100, blocked: 12100, total: 30600 },
    { timestamp: 'Day 6', timeLabel: 'Sat', detected: 6200, suspicious: 2400, blocked: 5300, total: 13900 },
    { timestamp: 'Day 7', timeLabel: 'Sun', detected: 7800, suspicious: 2900, blocked: 6900, total: 17600 },
  ],
  securityTrends: [
    { timeLabel: 'Mon', threatVolume: 19900, detectionConfidence: 94.5, robustness: 85.2, defenseRecovery: 91.0 },
    { timeLabel: 'Tue', threatVolume: 25100, detectionConfidence: 94.8, robustness: 86.0, defenseRecovery: 91.6 },
    { timeLabel: 'Wed', threatVolume: 28900, detectionConfidence: 95.0, robustness: 86.5, defenseRecovery: 92.0 },
    { timeLabel: 'Thu', threatVolume: 21900, detectionConfidence: 94.9, robustness: 86.8, defenseRecovery: 92.2 },
    { timeLabel: 'Fri', threatVolume: 30600, detectionConfidence: 95.4, robustness: 87.5, defenseRecovery: 93.0 },
    { timeLabel: 'Sat', threatVolume: 13900, detectionConfidence: 95.2, robustness: 87.2, defenseRecovery: 92.5 },
    { timeLabel: 'Sun', threatVolume: 17600, detectionConfidence: 95.1, robustness: 87.4, defenseRecovery: 92.6 },
  ],
};

export const DASHBOARD_DATA_30D: DashboardDataset = {
  ...DASHBOARD_DATA_24H,
  timeRange: '30D',
  snapshotTimestamp: 'Simulation snapshot • 30-Day Cumulative',
  postureScore: 86,
  postureRating: 'OPTIMAL RESILIENCE',
  kpis: [
    {
      ...DASHBOARD_DATA_24H.kpis[0],
      value: '372,940',
      numericValue: 372940,
      trend: '+22.4% monthly',
      sparkline: [1200, 1450, 1890, 2300, 2800, 3200, 3720],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[1],
      value: '318,400',
      numericValue: 318400,
      trend: '+19.8% monthly',
      sparkline: [1050, 1280, 1620, 2010, 2450, 2800, 3184],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[2],
      value: '96.2%',
      numericValue: 96.2,
      trend: '+3.1% monthly',
      sparkline: [92.0, 93.1, 93.8, 94.5, 95.2, 95.8, 96.2],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[3],
      value: '1.8%',
      numericValue: 1.8,
      trend: '-1.1% monthly',
      sparkline: [3.2, 2.9, 2.6, 2.3, 2.1, 1.9, 1.8],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[4],
      value: '88.9%',
      numericValue: 88.9,
      trend: '+7.6% monthly',
      sparkline: [78, 80.5, 82.8, 84.6, 86.4, 87.8, 88.9],
    },
    {
      ...DASHBOARD_DATA_24H.kpis[5],
      value: '93.7%',
      numericValue: 93.7,
      trend: '+8.9% monthly',
      sparkline: [84, 86, 88.2, 90.0, 91.5, 92.8, 93.7],
    },
  ],
  threatActivity: [
    { timestamp: 'Week 1', timeLabel: 'W1', detected: 68000, suspicious: 24000, blocked: 59000, total: 151000 },
    { timestamp: 'Week 2', timeLabel: 'W2', detected: 82000, suspicious: 29000, blocked: 71000, total: 182000 },
    { timestamp: 'Week 3', timeLabel: 'W3', detected: 94000, suspicious: 34000, blocked: 83000, total: 211000 },
    { timestamp: 'Week 4', timeLabel: 'W4', detected: 74400, suspicious: 26500, blocked: 65400, total: 166300 },
  ],
  securityTrends: [
    { timeLabel: 'W1', threatVolume: 151000, detectionConfidence: 93.8, robustness: 84.0, defenseRecovery: 89.5 },
    { timeLabel: 'W2', threatVolume: 182000, detectionConfidence: 94.6, robustness: 86.2, defenseRecovery: 91.2 },
    { timeLabel: 'W3', threatVolume: 211000, detectionConfidence: 95.5, robustness: 87.8, defenseRecovery: 92.8 },
    { timeLabel: 'W4', threatVolume: 166300, detectionConfidence: 96.2, robustness: 88.9, defenseRecovery: 93.7 },
  ],
};

export const DASHBOARD_DATA_MAP: Record<DashboardTimeRange, DashboardDataset> = {
  '24H': DASHBOARD_DATA_24H,
  '7D': DASHBOARD_DATA_7D,
  '30D': DASHBOARD_DATA_30D,
};
