// DEMO ONLY — replace with API data in later phases.
// These mock data structures provide visual telemetry, search index, notifications, and logs for Phase 4.

import {
  ThreatNodeData,
  MetricCardData,
  ActivityDataPoint,
  SearchItem,
  NotificationItem,
  DetailedScanLog,
  ReportDossier,
  RobustnessCase,
  UserSettings,
  DemoScanSample,
  ScanResult,
} from "@/types";

export const DEMO_METRICS: MetricCardData[] = [
  {
    id: "messages-scanned",
    title: "Messages Scanned",
    value: "12,458",
    change: "+18.4% today",
    changeType: "positive",
    description: "Total messages analyzed across all channels",
    iconName: "ScanLine",
    tag: "DEMO",
  },
  {
    id: "threats-detected",
    title: "Threats Detected",
    value: "237",
    change: "+4 new threats",
    changeType: "negative",
    description: "Identified phishing, spearphish & fraud attacks",
    iconName: "ShieldAlert",
    tag: "DEMO",
  },
  {
    id: "detection-accuracy",
    title: "Detection Accuracy",
    value: "99.2%",
    change: "+0.3% robust baseline",
    changeType: "positive",
    description: "Evaluated on adversarial phishing benchmark",
    iconName: "Cpu",
    tag: "DEMO",
  },
  {
    id: "average-response",
    title: "Average Response",
    value: "~1.3s",
    change: "Real-time AI pipeline",
    changeType: "neutral",
    description: "Dual model inference & robustness evaluation",
    iconName: "Zap",
    tag: "DEMO",
  },
];

export const DEMO_THREAT_NODES: ThreatNodeData[] = [
  {
    id: "node-1",
    position: [1.3, 0.6, 0.8],
    lat: 37.7749,
    lng: -122.4194,
    label: "San Francisco Node",
    type: "Credential Harvesting URL",
    threatLevel: "phishing",
    timestamp: "2 mins ago",
    intensity: 0.9,
  },
  {
    id: "node-2",
    position: [-1.2, 0.8, 0.7],
    lat: 51.5074,
    lng: -0.1278,
    label: "London Node",
    type: "Adversarial Homoglyph Attack",
    threatLevel: "adversarial",
    timestamp: "4 mins ago",
    intensity: 0.95,
  },
  {
    id: "node-3",
    position: [0.8, -0.9, 1.1],
    lat: 1.3521,
    lng: 103.8198,
    label: "Singapore Node",
    type: "Spear Phishing Email",
    threatLevel: "phishing",
    timestamp: "7 mins ago",
    intensity: 0.8,
  },
  {
    id: "node-4",
    position: [-0.9, -0.6, -1.2],
    lat: -33.8688,
    lng: 151.2093,
    label: "Sydney Node",
    type: "Suspicious QR/Redirect Link",
    threatLevel: "suspicious",
    timestamp: "12 mins ago",
    intensity: 0.65,
  },
  {
    id: "node-5",
    position: [0.3, 1.4, -0.7],
    lat: 52.52,
    lng: 13.405,
    label: "Berlin Node",
    type: "Zero-Width Character Obfuscation",
    threatLevel: "adversarial",
    timestamp: "15 mins ago",
    intensity: 0.88,
  },
  {
    id: "node-6",
    position: [-1.4, -0.3, 0.6],
    lat: -23.5505,
    lng: -46.6333,
    label: "São Paulo Node",
    type: "Verified Legitimate Mail",
    threatLevel: "safe",
    timestamp: "18 mins ago",
    intensity: 0.4,
  },
];

export const DEMO_ACTIVITY_DATA: ActivityDataPoint[] = [
  { time: "00:00", scanned: 420, threats: 8 },
  { time: "03:00", scanned: 310, threats: 5 },
  { time: "06:00", scanned: 680, threats: 14 },
  { time: "09:00", scanned: 1450, threats: 38 },
  { time: "12:00", scanned: 2100, threats: 52 },
  { time: "15:00", scanned: 1890, threats: 41 },
  { time: "18:00", scanned: 1320, threats: 29 },
  { time: "21:00", scanned: 890, threats: 16 },
];

export const DEMO_SAMPLE_MESSAGES: DemoScanSample[] = [
  {
    id: "sample-cred-harvesting",
    title: "Credential Harvesting",
    category: "Credential Harvester",
    mode: "text",
    content: "URGENT SECURITY ALERT: Your Microsoft 365 cloud credentials have been blocked due to suspicious sign-in from Moscow, RU. Click https://login-microsoft-secure-verify.net/reset?auth=9812 to restore immediate access.",
    expectedVerdict: "PHISHING DETECTED",
    threatLevel: "phishing",
    confidence: 98.4,
    signals: [
      "DKIM/SPF spoofing mismatch (envelope vs from)",
      "High urgency linguistic markers ('URGENT', 'blocked')",
      "Deceptive domain: login-microsoft-secure-verify.net",
      "Direct credential verification redirection lure",
    ],
    recommendation: "Do NOT click the link. Verify account security directly at official portal. Revoke active sessions.",
    tokens: [
      { text: "URGENT SECURITY ALERT:", isThreat: true, category: "urgency", explanation: "High pressure urgency marker used to induce panic." },
      { text: "Your Microsoft 365 cloud credentials have been", isThreat: false },
      { text: "blocked", isThreat: true, category: "urgency", explanation: "Fabricated account state coercion." },
      { text: "due to suspicious sign-in from Moscow, RU. Click", isThreat: false },
      { text: "https://login-microsoft-secure-verify.net/reset?auth=9812", isThreat: true, category: "url", explanation: "Deceptive domain mimicking authentic corporate identity." },
      { text: "to restore immediate access.", isThreat: false },
    ],
    explanations: [
      { id: "exp-1", title: "Artificial Urgency & Coercion", explanation: "The message constructs an immediate crisis requiring urgent action within minutes.", severity: "high", category: "Psychological Lure" },
      { id: "exp-2", title: "Brand Impersonation Domain", explanation: "Domain 'login-microsoft-secure-verify.net' is not registered by Microsoft Corporation.", severity: "high", category: "Domain Spoofing" },
      { id: "exp-3", title: "Credential Phishing Vector", explanation: "Directing the victim to an unauthenticated external login portal to harvest enterprise tokens.", severity: "high", category: "Attack Vector" },
    ],
  },
  {
    id: "sample-bec",
    title: "Business Email Compromise",
    category: "CEO / Supplier Fraud",
    mode: "text",
    content: "CONFIDENTIAL: Hi Mark, please immediately wire $24,800 to our newly updated European supplier escrow account #GB82-9910-2391 to clear the server hardware shipment before 5 PM EST today.",
    expectedVerdict: "FINANCIAL FRAUD / BEC",
    threatLevel: "phishing",
    confidence: 96.9,
    signals: [
      "Executive name spoofing / BEC syntax",
      "Time-sensitive wire transfer request",
      "Unverified supplier escrow account diversion",
      "Secrecy / Confidentiality isolation tactic",
    ],
    recommendation: "Halt all wire requests. Validate request through out-of-band phone confirmation with executive.",
    tokens: [
      { text: "CONFIDENTIAL:", isThreat: true, category: "impersonation", explanation: "Social engineering isolation tactic." },
      { text: "Hi Mark, please", isThreat: false },
      { text: "immediately wire $24,800", isThreat: true, category: "payment", explanation: "Urgent monetary disbursement instruction." },
      { text: "to our newly updated European supplier escrow account", isThreat: false },
      { text: "#GB82-9910-2391", isThreat: true, category: "payment", explanation: "Unverified third-party account number." },
      { text: "to clear the server hardware shipment before 5 PM EST today.", isThreat: false },
    ],
    explanations: [
      { id: "exp-1", title: "Social Engineering & Isolation", explanation: "Attacker marks request confidential to prevent target from consulting teammates.", severity: "high", category: "Social Engineering" },
      { id: "exp-2", title: "Unscheduled Financial Diversion", explanation: "Direct request to modify banking details and expedite funds transfer.", severity: "high", category: "BEC Indicator" },
    ],
  },
  {
    id: "sample-urgent-payment",
    title: "Urgent Payment / Overdue Invoice",
    category: "Payment Scam",
    mode: "text",
    content: "FINAL NOTICE: Invoice #INV-89104 is 30 days overdue. Immediate payment of $1,420.00 is required today to avoid legal collection fees and credit termination. Pay via: https://quick-invoice-gateway.co/pay?id=89104",
    expectedVerdict: "PAYMENT PHISHING DETECTED",
    threatLevel: "phishing",
    confidence: 95.7,
    signals: [
      "Threat of legal action & credit damage",
      "Unregistered payment gateway domain",
      "Fabricated invoice identifier",
    ],
    recommendation: "Do NOT submit payment. Cross-reference invoice number with official procurement ledger.",
    tokens: [
      { text: "FINAL NOTICE:", isThreat: true, category: "urgency", explanation: "High-pressure urgency intimidation." },
      { text: "Invoice #INV-89104 is 30 days overdue.", isThreat: false },
      { text: "Immediate payment of $1,420.00 is required today to avoid legal collection fees", isThreat: true, category: "payment", explanation: "Intimidation coercion for financial extraction." },
      { text: "and credit termination. Pay via:", isThreat: false },
      { text: "https://quick-invoice-gateway.co/pay?id=89104", isThreat: true, category: "url", explanation: "Unverified payment collector portal." },
    ],
    explanations: [
      { id: "exp-1", title: "Legal Intimidation Tactics", explanation: "Simulates impending legal consequences to override rational security checks.", severity: "medium", category: "Psychological Coercion" },
      { id: "exp-2", title: "Generic Invoice Phishing", explanation: "Targets accounts payable with fabricated reference numbers.", severity: "high", category: "Financial Scam" },
    ],
  },
  {
    id: "sample-password-reset",
    title: "Password Reset Scam",
    category: "Identity Theft",
    mode: "email",
    content: "From: Security Team <noreply@accounts-security-verify.org>\nSubject: Password Expiry Notification\n\nYour SSO password expires in 2 hours. To maintain access to internal corporate systems, verify your existing password now: http://auth-portal-sso.org/verify",
    expectedVerdict: "SSO CREDENTIAL HARVESTER",
    threatLevel: "phishing",
    confidence: 97.2,
    signals: [
      "Lookalike SSO domain (accounts-security-verify.org)",
      "Urgent artificial expiration timeline",
      "Demand for active password entry",
    ],
    recommendation: "Do not visit the link. Standard IT teams never ask users to enter passwords via email links.",
    tokens: [
      { text: "From: Security Team <noreply@accounts-security-verify.org>", isThreat: true, category: "impersonation", explanation: "Lookalike external domain mimicking corporate IT." },
      { text: "\nSubject: Password Expiry Notification\n\nYour SSO password expires in", isThreat: false },
      { text: "2 hours.", isThreat: true, category: "urgency", explanation: "Tight artificial deadline." },
      { text: "To maintain access to internal corporate systems,", isThreat: false },
      { text: "verify your existing password now:", isThreat: true, category: "credential", explanation: "Direct credential harvesting request." },
      { text: "http://auth-portal-sso.org/verify", isThreat: true, category: "url", explanation: "Insecure HTTP redirect to external domain." },
    ],
    explanations: [
      { id: "exp-1", title: "SSO Brand Impersonation", explanation: "Mimics enterprise Single Sign-On to capture high-privilege credentials.", severity: "high", category: "Authentication Spoof" },
      { id: "exp-2", title: "Insecure Transport Channel", explanation: "Uses unencrypted HTTP for credential submission.", severity: "high", category: "Protocol Vulnerability" },
    ],
  },
  {
    id: "sample-homoglyph",
    title: "Homoglyph Evasion",
    category: "Adversarial Attack",
    mode: "url",
    content: "Notice: An unauthorized transaction of $499.00 was authorized on your account. Review details and dispute here: http://pаypаl-security-verification.com/dispute?token=92819",
    expectedVerdict: "ADVERSARIAL HOMOGLYPH FLAGGED",
    threatLevel: "adversarial",
    confidence: 94.2,
    signals: [
      "Unicode Confusable: Cyrillic Small Letter A (U+0430) used in domain",
      "Adversarial perturbation recovered via NFKC normalization",
      "Newly registered spoof domain targeting consumer wallet",
    ],
    recommendation: "Quarantine immediately. Threat is using internationalized domain evasion to bypass basic filters.",
    tokens: [
      { text: "Notice: An unauthorized transaction of $499.00 was authorized on your account. Review details and dispute here:", isThreat: false },
      { text: "http://pаypаl-security-verification.com/dispute?token=92819", isThreat: true, category: "homoglyph", explanation: "Adversarial homoglyph: 'а' is Cyrillic (U+0430), not Latin 'a'." },
    ],
    explanations: [
      { id: "exp-1", title: "Adversarial Character Mutation", explanation: "Visual spoofing replaces Latin 'a' with Cyrillic 'а' to defeat standard regex keyword detectors.", severity: "high", category: "Evasion Technique" },
      { id: "exp-2", title: "Adversarial Defense Hardening", explanation: "PhishGuard-AR Unicode confusable engine normalized punycode representation back to standard string.", severity: "high", category: "Robustness Mechanism" },
    ],
  },
  {
    id: "sample-legitimate",
    title: "Legitimate Corporate Mail",
    category: "Benign Communication",
    mode: "text",
    content: "Team, the weekly engineering architecture synchronization will take place tomorrow at 10:00 AM in Conference Room B. Please review the attached agenda in Jira before the call.",
    expectedVerdict: "BENIGN / SAFE MESSAGE",
    threatLevel: "safe",
    confidence: 99.5,
    signals: [
      "Valid corporate vocabulary & neutral semantic sentiment",
      "Zero obfuscated glyphs or zero-width split tokens",
      "No external links, financial demands, or credential requests",
    ],
    recommendation: "No security action required. Message is verified benign corporate communication.",
    tokens: [
      { text: "Team, the weekly engineering architecture synchronization will take place tomorrow at 10:00 AM in Conference Room B. Please review the attached agenda in Jira before the call.", isThreat: false },
    ],
    explanations: [
      { id: "exp-1", title: "Authentic Operational Context", explanation: "Vocabulary and phrasing align with routine internal communications without manipulative intent.", severity: "low", category: "Benign Signal" },
      { id: "exp-2", title: "Zero Threat Indicators", explanation: "No deceptive links, zero-width characters, or credential harvesting payloads detected.", severity: "low", category: "Integrity Verified" },
    ],
  },
];

export const DEMO_SEARCH_ITEMS: SearchItem[] = [
  {
    id: "search-1",
    title: "Threat Scanner Console",
    category: "Navigation",
    description: "Scan suspicious text, URLs, email headers, and file attachments",
    href: "/scan",
    badge: "Scanner",
  },
  {
    id: "search-2",
    title: "Adversarial Robustness Lab",
    category: "Navigation",
    description: "Test perturbations, homoglyph mutations & defense hardening",
    href: "/robustness",
    badge: "Research",
  },
  {
    id: "search-3",
    title: "Security Operations Dashboard",
    category: "Navigation",
    description: "Live SOC threat telemetry, activity distributions, and metrics",
    href: "/dashboard",
    badge: "Telemetry",
  },
  {
    id: "search-4",
    title: "Scan Audit History",
    category: "Navigation",
    description: "Review audit records, filtered verdicts, and forensic evidence",
    href: "/history",
    badge: "Logs",
  },
  {
    id: "search-5",
    title: "Intelligence & Forensic Reports",
    category: "Navigation",
    description: "Export summary PDFs, robustness evaluations, and JSON dossiers",
    href: "/reports",
    badge: "Reports",
  },
  {
    id: "search-5b",
    title: "SOC Alert Center & Event Stream",
    category: "Navigation",
    description: "Review simulated security incidents, acknowledgements & SOC telemetry",
    href: "/alerts",
    badge: "Alerts",
  },
  {
    id: "search-6",
    title: "Platform Configuration",
    category: "Navigation",
    description: "Tune sensitivity thresholds, alert webhooks, and UI themes",
    href: "/settings",
    badge: "Settings",
  },
  {
    id: "search-7",
    title: "Homoglyph Character Evasion",
    category: "Threat Vector",
    description: "Unicode glyph replacement mimicking trusted brand domains (e.g. Cyrillic 'а')",
    href: "/robustness",
    badge: "Adversarial",
  },
  {
    id: "search-7b",
    title: "PHG-0001 — Microsoft 365 Credential Harvester",
    category: "Threat Vector",
    description: "Forensic record PHG-0001: high-urgency credential harvesting spoofing login portal",
    href: "/history",
    badge: "PHG-0001",
  },
  {
    id: "search-7c",
    title: "PHG-0002 — PayPal Cyrillic Homoglyph Evasion",
    category: "Threat Vector",
    description: "Forensic record PHG-0002: Unicode Cyrillic small letter a confusable attack",
    href: "/history",
    badge: "PHG-0002",
  },
  {
    id: "search-7d",
    title: "PHG-0003 — CEO Wire Transfer BEC",
    category: "Threat Vector",
    description: "Forensic record PHG-0003: Executive impersonation & financial routing diversion",
    href: "/history",
    badge: "PHG-0003",
  },
  {
    id: "search-8",
    title: "Zero-Width Space Obfuscation",
    category: "Threat Vector",
    description: "Invisible character insertions splitting malicious keywords",
    href: "/robustness",
    badge: "Adversarial",
  },
  {
    id: "search-9",
    title: "Multilingual DistilBERT Transformer",
    category: "Model Architecture",
    description: "104-language contextual transformer capturing semantic coercion intents",
    href: "/dashboard/intelligence",
    badge: "AI Engine",
  },
  {
    id: "search-10",
    title: "TF-IDF + Linear SVM Baseline",
    category: "Model Architecture",
    description: "High-throughput statistical n-gram classifier baseline (~2.4ms latency)",
    href: "/dashboard/intelligence",
    badge: "AI Engine",
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Suspicious Homoglyph URL Detected",
    message: "Global sensor flagged 'pаypаl-security-verification.com' with Cyrillic 'а' characters targeting executive inbox.",
    timestamp: "3 minutes ago",
    type: "threat",
    isRead: false,
    threatLevel: "adversarial",
  },
  {
    id: "notif-2",
    title: "Robustness Lab Simulation Completed",
    message: "Adversarial evasion benchmark completed: AR Hardening prevented 94.8% of character perturbation bypasses.",
    timestamp: "24 minutes ago",
    type: "model",
    isRead: false,
    threatLevel: "safe",
  },
  {
    id: "notif-3",
    title: "Daily Security Briefing Available",
    message: "Executive Phishing Summary report for 2026-09-18 has been compiled and is ready for export.",
    timestamp: "1 hour ago",
    type: "report",
    isRead: true,
    threatLevel: "safe",
  },
  {
    id: "notif-4",
    title: "High-Volume Credential Spike",
    message: "San Francisco telemetry node detected 38 consecutive Microsoft 365 token harvester requests.",
    timestamp: "2 hours ago",
    type: "threat",
    isRead: true,
    threatLevel: "phishing",
  },
];

export const DEMO_DETAILED_LOGS: DetailedScanLog[] = [
  {
    id: "LOG-9821",
    timestamp: "2026-09-18 13:42:10",
    target: "Microsoft 365 Account Suspension Notice",
    preview: "URGENT SECURITY ALERT: Your Microsoft 365 cloud credentials have been blocked...",
    type: "Email Header & Body",
    verdict: "PHISHING",
    confidence: "98.4%",
    threatLevel: "phishing",
    indicators: [
      "DKIM/SPF spoofing mismatch (envelope vs from)",
      "High urgency linguistic markers ('URGENT', 'blocked')",
      "Deceptive redirect URL: 'login-microsoft-secure-verify.net'",
    ],
    recommendation: "Block domain at enterprise gateway, revoke any cached sessions, and notify IT SecOps.",
  },
  {
    id: "LOG-9820",
    timestamp: "2026-09-18 12:15:33",
    target: "Quarterly Financial Statement Report.pdf",
    preview: "Clean corporate quarterly financial overview docx and summary sheet...",
    type: "File Attachment",
    verdict: "SAFE",
    confidence: "99.8%",
    threatLevel: "safe",
    indicators: [
      "Valid cryptographic signature matches corporate CA",
      "No embedded macros or deceptive hyperlink redirects",
      "Neutral sentiment and standard financial vocabulary",
    ],
    recommendation: "File is safe for standard internal distribution.",
  },
  {
    id: "LOG-9819",
    timestamp: "2026-09-18 11:04:19",
    target: "http://sec-updаte-auth.net/login?token=291",
    preview: "Notice: An unauthorized transaction of $499.00 was authorized on your account...",
    type: "URL Link",
    verdict: "ADVERSARIAL HOMOGLYPH",
    confidence: "94.2%",
    threatLevel: "adversarial",
    indicators: [
      "Homoglyph detected: Cyrillic Small Letter A (U+0430) used in domain",
      "Domain registration age < 48 hours (Newly Observed Domain)",
      "SSL Certificate issuer untrusted / Self-signed certificate",
    ],
    recommendation: "Quarantine message, add punycode representation 'xn--sec-updte-auth-0kb.net' to blocklist.",
  },
  {
    id: "LOG-9818",
    timestamp: "2026-09-18 09:28:45",
    target: "Internal Payroll Schedule Update",
    preview: "Team, please review the revised direct deposit cut-off dates for the upcoming holiday weekend...",
    type: "Text Content",
    verdict: "SAFE",
    confidence: "99.5%",
    threatLevel: "safe",
    indicators: [
      "Originates from verified internal HR exchange server",
      "Standard internal link referencing intranet.corp.local",
      "No anomalous character encodings or urgency coercions",
    ],
    recommendation: "No action required. Verified benign message.",
  },
  {
    id: "LOG-9817",
    timestamp: "2026-09-18 08:14:02",
    target: "Executive Wire Transfer Authorization Request",
    preview: "CONFIDENTIAL: Hi Mark, please immediately wire $24,800 to our newly updated European supplier...",
    type: "Text Content",
    verdict: "BLOCKED",
    confidence: "96.9%",
    threatLevel: "blocked",
    indicators: [
      "CEO Fraud / Business Email Compromise semantic pattern",
      "Bank routing number flagged in known fraudulent receiver database",
      "External sender spoofing executive displayName",
    ],
    recommendation: "Message auto-quarantined. Out-of-band voice confirmation required for any wire transfer.",
  },
  {
    id: "LOG-9816",
    timestamp: "2026-09-18 07:05:51",
    target: "Package Delivery Reschedule Notice - DHL Express",
    preview: "Your parcel #9812-482 could not be delivered due to missing postal address fee. Click link...",
    type: "Text Content",
    verdict: "SUSPICIOUS",
    confidence: "88.1%",
    threatLevel: "suspicious",
    indicators: [
      "Fee payment demand for generic package tracking",
      "Shortened Bitly link resolving to unverified third party landing page",
      "Sender IP geolocation outside expected carrier ASN",
    ],
    recommendation: "Advise recipient not to submit payment details. Verify tracking ID directly at dhl.com.",
  },
];

export const DEMO_REPORTS: ReportDossier[] = [
  {
    id: "REP-2026-Q3",
    title: "Executive Phishing Landscape & Threat Vector Dossier",
    category: "Executive Briefing",
    date: "2026-09-18",
    summary: "Quarterly forensic summary analyzing 12,400+ telemetry vectors across email, SMS, and messaging platforms with classification breakdown.",
    format: "PDF & JSON Dossier",
    threatScore: "94.8% Detection Rate",
    samplesAnalyzed: 12458,
    status: "VERIFIED",
    keyFindings: [
      "Credential harvesting remains the dominant attack vector (54.2% of all flagged samples).",
      "Homoglyph and zero-width character evasion attempts increased by 41% compared to Q2.",
      "Dual model ensemble (DistilBERT + SVM) reduced false positives to 0.8% across benchmark tests.",
    ],
  },
  {
    id: "REP-2026-AR",
    title: "Adversarial Robustness Evaluation & Evasion Resistance",
    category: "Technical AI Benchmark",
    date: "2026-09-15",
    summary: "Stress-testing NLP detectors under character perturbations, synonym replacement, homoglyphs, and adversarial perturbation attacks.",
    format: "PDF Technical Report",
    threatScore: "96.8% Hardened Resistance",
    samplesAnalyzed: 4500,
    status: "ACTIVE BENCHMARK",
    keyFindings: [
      "Standard static SVM accuracy drops from 97.4% to 29.2% under homoglyph perturbation.",
      "PhishGuard-AR normalization preprocessing pipeline recovers model accuracy to 96.8%.",
      "Multilingual DistilBERT attention layers successfully preserved context across 14 languages.",
    ],
  },
  {
    id: "REP-2026-SOC",
    title: "SOC Incident Forensic Response & Indicators of Compromise (IoC)",
    category: "Forensic Analysis",
    date: "2026-09-12",
    summary: "Curated dataset of high-severity phishing campaigns, malicious domain namespaces, and homoglyph mutation signatures.",
    format: "STIX 2.1 & JSON",
    threatScore: "237 High Severity IoCs",
    samplesAnalyzed: 890,
    status: "FORENSIC AUDIT",
    keyFindings: [
      "Identified 18 newly registered homoglyph domains impersonating enterprise SaaS portals.",
      "Mapped 4 distinct bulletproof hosting providers utilized in credential harvesting campaigns.",
      "Provided automated firewall rule definitions and regex signatures for SIEM ingestion.",
    ],
  },
];

export const DEMO_ROBUSTNESS_CASES: RobustnessCase[] = [
  {
    id: "case-homoglyph",
    name: "Cyrillic Homoglyph Replacement",
    category: "Character Evasion",
    originalText: "Your account requires immediate verification: http://login-paypal-verify.com to avoid suspension.",
    attackedText: "Your аccount requires immediаte verificаtion: http://login-pаypаl-verify.com to аvoid suspension.",
    attackType: "Latin 'a' replaced with Cyrillic 'а' (U+0430)",
    baselineVerdict: "PHISHING (Detected)",
    baselineConfidence: "97.4%",
    attackVerdict: "SAFE (Evasion Success)",
    attackConfidence: "32.1%",
    confidenceDrop: "-65.3%",
    hardenedVerdict: "PHISHING (Resisted)",
    hardenedConfidence: "96.8%",
    defenseMechanism: "Unicode NFKC normalization + Homoglyph confusable mapping",
  },
  {
    id: "case-zero-width",
    name: "Zero-Width Space Keyword Splitting",
    category: "Obfuscation",
    originalText: "Please confirm your password and banking credential details immediately.",
    attackedText: "Please confirm your pass​word and ban​king cred​ential details immediately.",
    attackType: "Zero-Width Spaces (U+200B) inserted inside critical keyword tokens",
    baselineVerdict: "PHISHING (Detected)",
    baselineConfidence: "95.8%",
    attackVerdict: "SAFE (False Negative)",
    attackConfidence: "41.0%",
    confidenceDrop: "-54.8%",
    hardenedVerdict: "PHISHING (Resisted)",
    hardenedConfidence: "95.2%",
    defenseMechanism: "Invisible character sanitization + Byte-level BPE tokenization",
  },
  {
    id: "case-synonym",
    name: "Urgency Synonym Substitution",
    category: "Semantic Perturbation",
    originalText: "URGENT ACTION REQUIRED: Transfer funds immediately to avoid legal penalty.",
    attackedText: "Crucial promptitude needed: Remit capital straightaway to avert juridical sanction.",
    attackType: "Thesaurus-based adversarial word substitution preserving threat intent",
    baselineVerdict: "PHISHING (Detected)",
    baselineConfidence: "96.1%",
    attackVerdict: "SUSPICIOUS (Degraded)",
    attackConfidence: "58.4%",
    confidenceDrop: "-37.7%",
    hardenedVerdict: "PHISHING (Resisted)",
    hardenedConfidence: "93.9%",
    defenseMechanism: "Multilingual DistilBERT semantic self-attention embeddings",
  },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
  theme: "dark",
  density: "comfortable",
  animations: true,
  reducedMotion: false,
  protectionMode: "adversarial-hardened",
  threatThreshold: 0.85,
  autoScan: true,
  notificationsEnabled: true,
  securityAlerts: true,
  dailySummary: false,
  compactNav: false,
};
