/**
 * PhishGuard-AR — Phase 9
 * Centralized Threat History Demo Dataset
 * 
 * 100% Frontend-Only — Deterministic Demonstration Data
 */

import { ThreatHistoryRecord } from '@/types';

export const DEMO_THREAT_HISTORY: ThreatHistoryRecord[] = [
  {
    id: 'PHG-0001',
    timestamp: '2026-09-18 14:42:08',
    input: 'URGENT: Your Microsoft 365 security token has expired. Re-authenticate immediately at https://auth-verify892.top/login to prevent service termination.',
    inputType: 'EMAIL',
    threatType: 'Credential Harvesting',
    verdict: 'PHISHING',
    severity: 'CRITICAL',
    confidence: 96.4,
    robustnessScore: 92.0,
    modelBranch: 'BAYESIAN_FUSION',
    indicators: [
      'High lexical urgency ("immediately", "prevent service termination")',
      'High Shannon entropy on domain auth-verify892.top (3.84 bits)',
      'Lookalike Microsoft SSO brand identity mimicry',
      'Unverified external redirection target',
    ],
    recommendation: 'Immediate perimeter firewall block on domain auth-verify892.top and invalidate active user OAuth tokens.',
    explanation: 'Simulated multi-modal model analysis flagged deceptive credential extraction syntax combined with unauthorized hosting infrastructure.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0001 Initial Access',
      technique: 'T1566.002 Spearphishing Link',
      description: 'Adversary creates fake identity portal to capture authentication tokens.',
    },
  },
  {
    id: 'PHG-0002',
    timestamp: '2026-09-18 13:15:32',
    input: 'Chase Alert: An unauthorized wire transfer of $4,850.00 was attempted from your account. If this was not you, cancel transaction at https://secure-chase-protection.net.',
    inputType: 'TEXT',
    threatType: 'Financial Impersonation',
    verdict: 'PHISHING',
    severity: 'CRITICAL',
    confidence: 95.2,
    robustnessScore: 89.0,
    modelBranch: 'BAYESIAN_FUSION',
    indicators: [
      'Monetary coercion ($4,850.00 transaction panic)',
      'Domain age delta < 48 hours imitating banking brand',
      'Call-to-action directs to unverified off-premise collector',
    ],
    recommendation: 'Quarantine SMS notification and flag domain across internal web security gateways.',
    explanation: 'Lexical SVM and Transformer consensus identified classic financial panic framing targeting consumer credentials.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0001 Initial Access',
      technique: 'T1566.001 Spearphishing Attachment / Link',
      description: 'Lure relies on fear of immediate financial loss.',
    },
  },
  {
    id: 'PHG-0003',
    timestamp: '2026-09-18 11:28:45',
    input: 'Аttentiоn: Yоur PаyPаl ассоunt hаs bееn restriсted. Vеrify nоw: https://pаypаl-sесurе-lоgin.соm (Cyrillic homoglyphs embedded).',
    inputType: 'EMAIL',
    threatType: 'Adversarial Homoglyph Attack',
    verdict: 'ADVERSARIAL',
    severity: 'CRITICAL',
    confidence: 96.8,
    robustnessScore: 95.0,
    modelBranch: 'DISTILBERT_TRANSFORMER',
    indicators: [
      '14 Cyrillic confusable characters (U+0430, U+043E, U+0441)',
      'Intended evasion of standard ASCII tokenizers',
      'Neutralized via Phase 6 Unicode Canonicalization defense',
    ],
    recommendation: 'Enable Unicode script boundary enforcement across enterprise email relays.',
    explanation: 'Adversary embedded mixed Cyrillic/Latin script to evade regex filters. Successfully neutralized by PhishGuard-AR adversarial robustness layer.',
    isHomoglyph: true,
    attackContext: {
      mitreTactic: 'TA0005 Defense Evasion',
      technique: 'T1036.005 Masquerading: Match Legitimate Name',
      description: 'Homoglyph substitution creates visual similarity while altering byte encodings.',
    },
  },
  {
    id: 'PHG-0004',
    timestamp: '2026-09-18 09:54:19',
    input: 'Internal HR Update: Form W-2 tax documents for the current fiscal period are now available. Review your confidential earnings statement at https://hr-portal-internal.co/w2.',
    inputType: 'EMAIL',
    threatType: 'Corporate Payroll Spoof',
    verdict: 'SUSPICIOUS',
    severity: 'HIGH',
    confidence: 82.4,
    robustnessScore: 86.0,
    modelBranch: 'TF_IDF_SVM',
    indicators: [
      'Domain hr-portal-internal.co registered via commercial proxy',
      'Absence of internal Active Directory single-sign-on headers',
      'Lure targets sensitive employee tax documentation',
    ],
    recommendation: 'Subject payload to manual SOC review; verify sender SPF/DKIM envelope alignment.',
    explanation: 'Moderate suspicion due to off-premise domain usage imitating internal human resources portal.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0001 Initial Access',
      technique: 'T1566.002 Spearphishing Link',
      description: 'Tax and payroll documentation lure targeting employee credentials.',
    },
  },
  {
    id: 'PHG-0005',
    timestamp: '2026-09-17 18:30:11',
    input: 'WICHTIG: Ihr Deutsche Bank Sicherheitszertifikat läuft in 24 Stunden ab. Bitte aktualisieren Sie Ihre Zugangsdaten unter https://deutschebank-sicherheit.cloud/de.',
    inputType: 'EMAIL',
    threatType: 'Multilingual Banking Phish',
    verdict: 'PHISHING',
    severity: 'CRITICAL',
    confidence: 94.6,
    robustnessScore: 94.0,
    modelBranch: 'DISTILBERT_TRANSFORMER',
    indicators: [
      'German language credential harvesting ("Zugangsdaten")',
      'Cloud storage endpoint hosting unauthorized form',
      'Temporal deadline pressure ("in 24 Stunden")',
    ],
    recommendation: 'Sinkhole domain deutschebank-sicherheit.cloud and notify regional incident responders.',
    explanation: 'Multilingual DistilBERT evaluated German token embeddings and identified coercive banking lure with 94.6% confidence.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0001 Initial Access',
      technique: 'T1566.002 Spearphishing Link',
      description: 'Cross-border multilingual phishing campaign targeting European banking customers.',
    },
  },
  {
    id: 'PHG-0006',
    timestamp: '2026-09-17 15:12:00',
    input: 'Quarterly Product Review: Team, please review the attached slide deck ahead of our Thursday sync at 2:00 PM EST in Conference Room 4B.',
    inputType: 'EMAIL',
    threatType: 'Legitimate Internal Communication',
    verdict: 'SAFE',
    severity: 'SAFE',
    confidence: 3.2,
    robustnessScore: 97.0,
    modelBranch: 'BAYESIAN_FUSION',
    indicators: [
      'Zero external credential requests',
      'Valid corporate SPF/DKIM cryptographic signatures',
      'Standard neutral workplace scheduling vocabulary',
    ],
    recommendation: 'Permit delivery to inbox. No security countermeasure required.',
    explanation: 'Clean baseline message with zero adversarial perturbation, low lexical entropy, and authentic sender alignment.',
    isHomoglyph: false,
  },
  {
    id: 'PHG-0007',
    timestamp: '2026-09-17 12:44:28',
    input: 'https://bit.ly/3xX9kLm?redirect=http%3A%2F%2F192.168.1.55%2Fcorporate-sso-login.php',
    inputType: 'URL',
    threatType: 'Multi-Hop URL Cloaking',
    verdict: 'BLOCKED',
    severity: 'CRITICAL',
    confidence: 98.1,
    robustnessScore: 91.0,
    modelBranch: 'TF_IDF_SVM',
    indicators: [
      'URL shortener hiding raw IP address destination',
      'Multi-hop HTTP 302 redirect chain',
      'Target path masquerades as corporate-sso-login',
    ],
    recommendation: 'Block at DNS resolver level and log source IP in threat intelligence SIEM feed.',
    explanation: 'Recursive link unfurling revealed direct IP redirect designed to evade static domain reputation databases.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0005 Defense Evasion',
      technique: 'T1027 Obfuscated / Encoded Files or Information',
      description: 'Shortened and nested URLs cloak malicious IP infrastructure.',
    },
  },
  {
    id: 'PHG-0008',
    timestamp: '2026-09-16 20:05:14',
    input: 'Invoice_Overdue_INV-98211.pdf.exe',
    inputType: 'FILE',
    threatType: 'Double Extension Executable',
    verdict: 'BLOCKED',
    severity: 'CRITICAL',
    confidence: 99.4,
    robustnessScore: 96.0,
    modelBranch: 'BAYESIAN_FUSION',
    indicators: [
      'Double extension masking Windows PE executable',
      'Mismatched MIME type (application/x-dosexec)',
      'Embedded zero-width space prior to .exe suffix',
    ],
    recommendation: 'Quarantine attachment immediately and run sandbox detonation.',
    explanation: 'High-risk payload utilizing double file extensions to trick users into executing malicious code under the guise of an invoice.',
    isHomoglyph: false,
    attackContext: {
      mitreTactic: 'TA0005 Defense Evasion',
      technique: 'T1036.007 Double File Extension',
      description: 'File masquerading to deceive user and operating system file associations.',
    },
  },
  {
    id: 'PHG-0009',
    timestamp: '2026-09-16 16:22:50',
    input: 'Package Delivery Issue: We attempted delivery of your parcel today. Schedule redelivery at https://fedx-parcel-tracking.vip.',
    inputType: 'TEXT',
    threatType: 'Courier Brand Spoofing',
    verdict: 'PHISHING',
    severity: 'HIGH',
    confidence: 88.7,
    robustnessScore: 90.0,
    modelBranch: 'TF_IDF_SVM',
    indicators: [
      'Lookalike courier domain typo-squatting ("fedx" missing "e")',
      '.vip high-risk top level domain',
      'Mobile parcel notification framing',
    ],
    recommendation: 'Block domain and alert mobile users regarding courier parcel smishing lures.',
    explanation: 'Typo-squatted brand imitation targeting users with fake redelivery fee requests.',
    isHomoglyph: false,
  },
  {
    id: 'PHG-0010',
    timestamp: '2026-09-16 10:14:02',
    input: 'All-Hands Meeting Q3 Recording & Notes are now live on the internal intranet wiki: https://wiki.internal.corp/all-hands-q3.',
    inputType: 'URL',
    threatType: 'Internal Knowledge Base',
    verdict: 'SAFE',
    severity: 'SAFE',
    confidence: 2.1,
    robustnessScore: 98.0,
    modelBranch: 'BAYESIAN_FUSION',
    indicators: [
      'Authenticated corporate intranet domain',
      'Zero external form targets',
      'TLS certificate validated against enterprise CA',
    ],
    recommendation: 'No threat detected. Allow normal employee access.',
    explanation: 'Verified internal infrastructure with authentic cryptographic credentials and clean lexical markers.',
    isHomoglyph: false,
  },
];
